/**
 * Service category definitions matching Phase 3 & 4 specs.
 */
export const SERVICE_CATEGORIES = [
  {
    id: "electrical",
    name: "Electrical",
    slug: "electrical",
    icon: "⚡",
    description: "Wiring, switches, fans, MCB, inverter setup, and electrical repairs",
    color: "#F59E0B",
    count: 42,
    startingPrice: 149,
    estimatedTime: "30-45 mins",
    bannerImage: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=80",
    warranty: "30-Day Warranty on all installations & wiring repairs",
  },
  {
    id: "plumbing",
    name: "Plumbing",
    slug: "plumbing",
    icon: "🔧",
    description: "Pipe repairs, tap leaks, bathroom fitting, gully trap, and drainage",
    color: "#3B82F6",
    count: 38,
    startingPrice: 199,
    estimatedTime: "30-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&q=80",
    warranty: "30-Day Free Leakage Re-work Warranty",
  },
  {
    id: "ac",
    name: "AC Repair & Service",
    slug: "ac",
    icon: "❄️",
    description: "Foam jet wash, gas refill, installation, noise fix, and maintenance",
    color: "#06B6D4",
    count: 29,
    startingPrice: 499,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80",
    warranty: "90-Day Compressor & Gas Refill Guarantee",
  },
  {
    id: "carpentry",
    name: "Carpentry",
    slug: "carpentry",
    icon: "🪚",
    description: "Furniture repair, door locks, hinges, wardrobe assembly, and woodwork",
    color: "#D97706",
    count: 35,
    startingPrice: 249,
    estimatedTime: "45-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&q=80",
    warranty: "30-Day Workmanship Cover",
  },
  {
    id: "cleaning",
    name: "Deep Cleaning",
    slug: "cleaning",
    icon: "🧹",
    description: "Full home, kitchen, sofa shampooing, bathroom, and balcony cleaning",
    color: "#10B981",
    count: 50,
    startingPrice: 399,
    estimatedTime: "2-4 hours",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "100% Satisfaction Re-cleaning Guarantee within 24h",
  },
  {
    id: "painting",
    name: "Painting",
    slug: "painting",
    icon: "🎨",
    description: "Interior, exterior, waterproofing, texture paint, and damp treatment",
    color: "#8B5CF6",
    count: 24,
    startingPrice: 999,
    estimatedTime: "1-3 days",
    bannerImage: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&q=80",
    warranty: "1-Year Paint Peeling & Waterproofing Warranty",
  },
  {
    id: "civil",
    name: "Civil & Masonry",
    slug: "civil",
    icon: "🏗️",
    description: "Tile fixing, wall plastering, concrete repairs, and wall cracks",
    color: "#64748B",
    count: 18,
    startingPrice: 499,
    estimatedTime: "2-6 hours",
    bannerImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80",
    warranty: "6-Month Structural Integrity Warranty",
  },
  {
    id: "inspection",
    name: "Home Inspection",
    slug: "inspection",
    icon: "🔍",
    description: "Pre-purchase home audit, electrical thermal check, and damp scan",
    color: "#3B82F6",
    count: 12,
    startingPrice: 1499,
    estimatedTime: "2-3 hours",
    bannerImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80",
    warranty: "Comprehensive 50-Point Audit Report Included",
  },
  {
    id: "security",
    name: "Security & CCTV",
    slug: "security",
    icon: "🛡️",
    description: "CCTV camera setup, smart door locks, video doorbell, and intruder alarms",
    color: "#143560",
    count: 16,
    startingPrice: 699,
    estimatedTime: "1-2 hours",
    bannerImage: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=1200&q=80",
    warranty: "1-Year Hardware & Wiring Warranty",
  },
  {
    id: "glass",
    name: "Glass & Windows",
    slug: "glass",
    icon: "🪟",
    description: "Glass door alignment, sliding window mesh, mirror fitting, and frosted film",
    color: "#38BDF8",
    count: 15,
    startingPrice: 299,
    estimatedTime: "30-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80",
    warranty: "30-Day Alignment & Seal Guarantee",
  },
  {
    id: "smart-home",
    name: "Smart Home",
    slug: "smart-home",
    icon: "🏠",
    description: "Smart switches, Alexa/Google Home voice automation, and WiFi mesh",
    color: "#A855F7",
    count: 20,
    startingPrice: 599,
    estimatedTime: "1-2 hours",
    bannerImage: "https://images.unsplash.com/photo-1558002038-1055907df827?w=1200&q=80",
    warranty: "1-Year Automation Config Support",
  },
  {
    id: "pest-control",
    name: "Pest Control",
    slug: "pest-control",
    icon: "🐛",
    description: "Cockroach, termite, bed bugs, ant, and mosquito herbal treatment",
    color: "#EF4444",
    count: 27,
    startingPrice: 699,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    warranty: "90-Day Re-treatment Guarantee",
  },
  {
    id: "false-ceiling",
    name: "False Ceiling",
    slug: "false-ceiling",
    icon: "🪵",
    description: "POP, Gypsum board ceiling design, cove lighting, and repair",
    color: "#EAB308",
    count: 14,
    startingPrice: 1999,
    estimatedTime: "1-2 days",
    bannerImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80",
    warranty: "2-Year Anti-Sagging Warranty",
  },
  {
    id: "flooring",
    name: "Flooring & Tiling",
    slug: "flooring",
    icon: "🧱",
    description: "Wooden flooring installation, marble polishing, and tile grouting",
    color: "#B45309",
    count: 19,
    startingPrice: 899,
    estimatedTime: "3-8 hours",
    bannerImage: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&q=80",
    warranty: "1-Year Shine & Grouting Warranty",
  },
  {
    id: "interior-repair",
    name: "Interior Repair",
    slug: "interior-repair",
    icon: "🔨",
    description: "Modular kitchen repair, soft-close hinges, wardrobe touch-ups, and drawers",
    color: "#EC4899",
    count: 31,
    startingPrice: 349,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "90-Day Hardware & Fitting Warranty",
  },
] as const;

/* ─── Detailed Services Map by Category ─── */

export const CATEGORY_SERVICES_MAP: Record<string, any[]> = {
  electrical: [
    {
      id: "elec-1",
      name: "Switch & Socket Repair / Replacement",
      slug: "switch-socket-repair",
      shortDescription: "Fix faulty switches, burnt sockets, or install new modular switchboards.",
      basePrice: 199,
      discountedPrice: 149,
      duration: 30,
      rating: 4.8,
      reviewCount: 920,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-2",
      name: "Ceiling Fan Installation & Repair",
      slug: "ceiling-fan-installation",
      shortDescription: "Assembly, heavy hook mounting, regulator replacement, or noise troubleshooting.",
      basePrice: 299,
      discountedPrice: 199,
      duration: 45,
      rating: 4.9,
      reviewCount: 650,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-3",
      name: "MCB & Fuse Box Circuit Repair",
      slug: "mcb-fuse-box-repair",
      shortDescription: "Troubleshoot frequent MCB trips, neutral short circuits, and phase balancing.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.7,
      reviewCount: 480,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-4",
      name: "Chandelier & Decorative Light Mounting",
      slug: "chandelier-mounting",
      shortDescription: "Safe ceiling drilling, heavy-duty anchor installation, and electrical wiring.",
      basePrice: 799,
      discountedPrice: 599,
      duration: 60,
      rating: 4.8,
      reviewCount: 310,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
  ],
  plumbing: [
    {
      id: "plumb-1",
      name: "Tap Leakage & Spout Replacement",
      slug: "tap-leakage-replacement",
      shortDescription: "Fix dripping taps, washer replacement, or install modern mixer taps.",
      basePrice: 299,
      discountedPrice: 199,
      duration: 30,
      rating: 4.9,
      reviewCount: 1250,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-2",
      name: "Drainage & Wash Basin Unclogging",
      slug: "drainage-unclogging",
      shortDescription: "Clear stubborn blockages in wash basins, floor traps, and kitchen sinks.",
      basePrice: 449,
      discountedPrice: 299,
      duration: 45,
      rating: 4.8,
      reviewCount: 880,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-3",
      name: "Flush Tank & Western Toilet Repair",
      slug: "flush-tank-toilet-repair",
      shortDescription: "Fix continuously running flush tanks, syphon kit replacement, or jet spray.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.7,
      reviewCount: 540,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-4",
      name: "Water Heater Geyser Connection & Piping",
      slug: "geyser-connection-piping",
      shortDescription: "Connecting hot/cold inlet pipes, pressure release valve, and leak check.",
      basePrice: 599,
      discountedPrice: 449,
      duration: 60,
      rating: 4.9,
      reviewCount: 410,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
  ],
  ac: [
    {
      id: "ac-1",
      name: "Split AC Foam Jet Deep Servicing",
      slug: "split-ac-foam-servicing",
      shortDescription: "High-pressure foam jet wash of cooling coils, blower, tray, and outdoor unit.",
      basePrice: 699,
      discountedPrice: 499,
      duration: 45,
      rating: 4.9,
      reviewCount: 2100,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
    {
      id: "ac-2",
      name: "AC Gas Leakage Check & Top-Up (R32/R410)",
      slug: "ac-gas-leakage-topup",
      shortDescription: "Nitrogen testing, brazing copper pipe leak, vacuuming, and eco refrigerant fill.",
      basePrice: 2499,
      discountedPrice: 1899,
      duration: 90,
      rating: 4.8,
      reviewCount: 1450,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
    {
      id: "ac-3",
      name: "Split AC Un-installation & Re-installation",
      slug: "split-ac-installation",
      shortDescription: "Safe refrigerant recovery, wall bracket mounting, copper piping & testing.",
      basePrice: 1799,
      discountedPrice: 1399,
      duration: 120,
      rating: 4.7,
      reviewCount: 890,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
  ],
  carpentry: [
    {
      id: "carp-1",
      name: "Door Lock & Handle Fitting",
      slug: "door-lock-fitting",
      shortDescription: "Installation of mortise lock, door latch, hinges, and alignment.",
      basePrice: 449,
      discountedPrice: 299,
      duration: 45,
      rating: 4.8,
      reviewCount: 610,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      category: { slug: "carpentry", name: "Carpentry" },
    },
    {
      id: "carp-2",
      name: "Furniture Assembly (IKEA / Wooden)",
      slug: "furniture-assembly",
      shortDescription: "Professional assembly of wardrobes, beds, TV units, and study tables.",
      basePrice: 799,
      discountedPrice: 549,
      duration: 90,
      rating: 4.9,
      reviewCount: 780,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&q=80",
      category: { slug: "carpentry", name: "Carpentry" },
    },
  ],
  cleaning: [
    {
      id: "clean-1",
      name: "Full House Deep Cleaning (2 BHK)",
      slug: "full-house-deep-cleaning",
      shortDescription: "Includes kitchen degreasing, bathroom descaling, balcony wash, and floor buffing.",
      basePrice: 3999,
      discountedPrice: 2999,
      duration: 240,
      rating: 4.9,
      reviewCount: 1800,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
      category: { slug: "cleaning", name: "Deep Cleaning" },
    },
    {
      id: "clean-2",
      name: "3-Seater Sofa Shampoo & Extraction",
      slug: "sofa-shampoo-cleaning",
      shortDescription: "Deep foam shampooing and vacuum moisture extraction for fabric sofas.",
      basePrice: 1199,
      discountedPrice: 899,
      duration: 90,
      rating: 4.8,
      reviewCount: 950,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
      category: { slug: "cleaning", name: "Deep Cleaning" },
    },
  ],
  painting: [
    {
      id: "paint-1",
      name: "Full Home Wall Painting & Putty",
      slug: "full-home-wall-painting",
      shortDescription: "Asian Paints premium emulsion, double coat putty, primer & dust-free sanding.",
      basePrice: 8999,
      discountedPrice: 6999,
      duration: 1440,
      rating: 4.9,
      reviewCount: 720,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&q=80",
      category: { slug: "painting", name: "Painting" },
    },
    {
      id: "paint-2",
      name: "Waterproofing & Wall Damp Treatment",
      slug: "waterproofing-damp-treatment",
      shortDescription: "Doctor Fixit waterproofing, damp lock primer, and wall seepage repair.",
      basePrice: 2499,
      discountedPrice: 1899,
      duration: 180,
      rating: 4.8,
      reviewCount: 510,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&q=80",
      category: { slug: "painting", name: "Painting" },
    },
  ],
  civil: [
    {
      id: "civil-1",
      name: "Tile Replacement & Grouting Repair",
      slug: "tile-replacement-grouting",
      shortDescription: "Fix broken floor/wall tiles, epoxy grouting, and anti-skid bathroom tiling.",
      basePrice: 899,
      discountedPrice: 649,
      duration: 120,
      rating: 4.7,
      reviewCount: 380,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80",
      category: { slug: "civil", name: "Civil & Masonry" },
    },
  ],
  inspection: [
    {
      id: "insp-1",
      name: "Full Home Pre-Purchase Inspection",
      slug: "full-home-inspection",
      shortDescription: "50-point thermal audit for dampness, electrical hazards, and structural cracks.",
      basePrice: 1999,
      discountedPrice: 1499,
      duration: 180,
      rating: 4.9,
      reviewCount: 290,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80",
      category: { slug: "inspection", name: "Home Inspection" },
    },
  ],
  security: [
    {
      id: "sec-1",
      name: "CCTV Camera Installation & Wiring",
      slug: "cctv-camera-installation",
      shortDescription: "HD dome/bullet CCTV camera mounting, DVR configuration & mobile app sync.",
      basePrice: 999,
      discountedPrice: 699,
      duration: 90,
      rating: 4.9,
      reviewCount: 640,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
      category: { slug: "security", name: "Security & CCTV" },
    },
  ],
  glass: [
    {
      id: "glass-1",
      name: "Sliding Window Glass & Mesh Fitting",
      slug: "sliding-window-glass-mesh",
      shortDescription: "Mosquito mesh sliding track fitting, toughened glass replacement, and rollers.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 420,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
      category: { slug: "glass", name: "Glass & Windows" },
    },
  ],
  "smart-home": [
    {
      id: "smart-1",
      name: "Smart Switch & Voice Automation Setup",
      slug: "smart-switch-voice-automation",
      shortDescription: "Convert existing switchboards to Alexa/Google Home smart app control.",
      basePrice: 899,
      discountedPrice: 599,
      duration: 60,
      rating: 4.9,
      reviewCount: 510,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80",
      category: { slug: "smart-home", name: "Smart Home" },
    },
  ],
  "pest-control": [
    {
      id: "pest-1",
      name: "Herbal Cockroach & Ant Control",
      slug: "herbal-cockroach-ant-control",
      shortDescription: "Odorless gel baiting & eco spray treatment with 90-day protection guarantee.",
      basePrice: 899,
      discountedPrice: 699,
      duration: 60,
      rating: 4.8,
      reviewCount: 1120,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      category: { slug: "pest-control", name: "Pest Control" },
    },
  ],
  appliance: [
    {
      id: "app-1",
      name: "Washing Machine Repair & Servicing",
      slug: "washing-machine-repair",
      shortDescription: "Fix spin noise, drum vibration, PCB board, motor, and water inlet valve.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 1350,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80",
      category: { slug: "appliance", name: "Appliance Repair" },
    },
  ],
  marble: [
    {
      id: "marb-1",
      name: "Diamond Italian Marble Polishing",
      slug: "diamond-italian-marble-polishing",
      shortDescription: "Multi-stage diamond pad floor grinding, mirror shine crystallization, and sealant.",
      basePrice: 1499,
      discountedPrice: 999,
      duration: 240,
      rating: 4.9,
      reviewCount: 390,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=600&q=80",
      category: { slug: "marble", name: "Marble Polishing" },
    },
  ],
  "interior-repair": [
    {
      id: "int-1",
      name: "Modular Kitchen Cabinet & Drawer Repair",
      slug: "modular-kitchen-cabinet-repair",
      shortDescription: "Hydraulic hinge replacement, soft-close channel alignment, and drawer repair.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 580,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
      category: { slug: "interior-repair", name: "Interior Repair" },
    },
  ],
};

/* ─── Category Technicians Map ─── */

export const CATEGORY_TECHNICIANS_MAP: Record<string, any[]> = {
  electrical: [
    {
      id: "tech-1",
      displayName: "Suresh Reddy",
      avatar: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&q=80",
      status: "available",
      experience: 7,
      rating: 4.9,
      reviewCount: 340,
      completedJobs: 620,
      serviceRadius: 8,
      specializations: ["Switchboards", "MCB Wiring", "Inverter Setup"],
      verificationStatus: "verified",
    },
    {
      id: "tech-2",
      displayName: "Ramesh Babu",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
      status: "busy",
      experience: 5,
      rating: 4.8,
      reviewCount: 180,
      completedJobs: 390,
      serviceRadius: 12,
      specializations: ["Ceiling Fans", "Chandelier Wiring"],
      verificationStatus: "verified",
    },
  ],
  plumbing: [
    {
      id: "tech-3",
      displayName: "Mahesh Kumar",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
      status: "available",
      experience: 8,
      rating: 4.9,
      reviewCount: 410,
      completedJobs: 850,
      serviceRadius: 6,
      specializations: ["Pipe Leakages", "Bathroom Fittings", "Drain Unclogging"],
      verificationStatus: "verified",
    },
  ],
  ac: [
    {
      id: "tech-4",
      displayName: "Rajesh Varma",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&q=80",
      status: "available",
      experience: 9,
      rating: 4.9,
      reviewCount: 530,
      completedJobs: 1100,
      serviceRadius: 10,
      specializations: ["Foam Jet Washing", "R32 Gas Charging", "Inverter AC"],
      verificationStatus: "verified",
    },
  ],
};

/* ─── Category FAQs Map ─── */

export const CATEGORY_FAQS_MAP: Record<string, any[]> = {
  electrical: [
    {
      question: "Do I need to supply electrical wires or switches?",
      answer: "No, our technician carries high-grade certified wiring, copper switches, and spares. If you already have your own fixtures, we will charge only for installation.",
    },
    {
      question: "Are your electrical repairs covered by a warranty?",
      answer: "Yes! All electrical installations and wiring repairs come with our 30-Day Home-e-Fix Re-work Warranty.",
    },
  ],
  plumbing: [
    {
      question: "What if the leakage starts again after the plumber leaves?",
      answer: "Every plumbing repair is covered by a 30-day leakage warranty. If a leak persists, request a free re-visit via the app, and our senior plumber will fix it.",
    },
  ],
  ac: [
    {
      question: "What is included in Split AC Foam Jet Deep Servicing?",
      answer: "It includes high-pressure foam jet washing of indoor cooling coils, blower wheel, drain tray, air filters, and high-pressure water spray on the outdoor condenser unit.",
    },
    {
      question: "How do I know if my AC requires a gas refill?",
      answer: "Common signs include reduced cooling, ice formation on the indoor unit's copper pipes, or a continuous ticking sound from the compressor.",
    },
  ],
};

/* ─── App Config ─── */

export const APP_CONFIG = {
  name: "Home-e-Fix",
  tagline: "Fixing Homes. Earning Trust.",
  description:
    "Home-e-Fix is your trusted Urban Company–style marketplace for all home services. Book verified professionals for electrical, plumbing, AC, cleaning, painting, and 10+ categories.",
  supportEmail: "support@homeefix.com",
  supportPhone: "+91 1800 123 4567",
  socialLinks: {
    facebook: "https://facebook.com/homeefix",
    instagram: "https://instagram.com/homeefix",
    twitter: "https://twitter.com/homeefix",
    linkedin: "https://linkedin.com/company/homeefix",
    youtube: "https://youtube.com/@homeefix",
  },
  playStoreLink: "#",
  appStoreLink: "#",
} as const;

export const POPULAR_SERVICES = [
  {
    id: "pop-ac-clean",
    name: "Split AC Foam Deep Jet Servicing",
    slug: "split-ac-foam-servicing",
    shortDescription: "Complete indoor & outdoor unit foam cleaning with high-pressure jet spray.",
    basePrice: 699,
    discountedPrice: 499,
    duration: 45,
    rating: 4.8,
    reviewCount: 1420,
    isPopular: true,
    category: { slug: "ac", name: "AC Repair & Service" },
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&q=80",
  },
  {
    id: "pop-plumb-leak",
    name: "Bathroom Leakage & Tap Repair",
    slug: "bathroom-leakage-tap-repair",
    shortDescription: "Fix leaking taps, flush tanks, pipe joints with 30-day warranty.",
    basePrice: 349,
    discountedPrice: 199,
    duration: 30,
    rating: 4.9,
    reviewCount: 980,
    isPopular: true,
    category: { slug: "plumbing", name: "Plumbing" },
    thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=500&q=80",
  },
  {
    id: "pop-elec-mcb",
    name: "Switch & Socket Installation / Repair",
    slug: "switch-socket-installation",
    shortDescription: "Replacement of burned switches, sockets, MCB trip troubleshooting.",
    basePrice: 249,
    discountedPrice: 149,
    duration: 30,
    rating: 4.7,
    reviewCount: 760,
    isPopular: true,
    category: { slug: "electrical", name: "Electrical" },
    thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&q=80",
  },
  {
    id: "pop-sofa-clean",
    name: "3-Seater Fabric Sofa Shampooing",
    slug: "sofa-shampoo-cleaning",
    shortDescription: "Deep extraction shampooing to remove tough stains, dust mites & odor.",
    basePrice: 1199,
    discountedPrice: 899,
    duration: 90,
    rating: 4.8,
    reviewCount: 650,
    isPopular: true,
    category: { slug: "cleaning", name: "Deep Cleaning" },
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=500&q=80",
  },
];

export const EMERGENCY_SERVICES = [
  {
    id: "emg-burst",
    title: "Major Pipe Burst & Water Overflow",
    icon: "🚨",
    arrival: "20-30 Mins",
    description: "Urgent valve shutoff and emergency pipe clamping.",
  },
  {
    id: "emg-power",
    title: "Total Power Blackout / MCB Burnout",
    icon: "⚡",
    arrival: "25-30 Mins",
    description: "Immediate emergency electrician for main line trip.",
  },
];

export const WHY_HOMEEFIX = [
  {
    id: "verified-pros",
    icon: "🛡️",
    title: "100% Background Verified Pros",
    description: "Every technician undergoes police verification and skill tests.",
    highlight: "Top 5% accepted",
  },
  {
    id: "fixed-pricing",
    icon: "💰",
    title: "Transparent Upfront Pricing",
    description: "No hidden inspection fees or surprise bills.",
    highlight: "Zero hidden charges",
  },
];

export const HOMEEFIX_PROMISE = [
  {
    title: "Damage Protection Cover",
    description: "Up to ₹10,000 insurance coverage against accidental damages.",
    icon: "🛡️",
  },
];

export const TESTIMONIALS = [
  {
    userName: "Priya Sharma",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    rating: 5,
    date: "2026-08-01",
    comment: "The AC foam deep cleaning was unbelievable! Airflow doubled.",
    serviceName: "AC Foam Deep Cleaning",
    isVerified: true,
    helpfulCount: 28,
  },
];

export const BLOG_ARTICLES = [
  {
    id: "blog-ac-maintenance",
    title: "5 Critical Signs Your AC Needs Gas Refill & Servicing",
    category: "Appliance Care",
    date: "Aug 02, 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&q=80",
    snippet: "Is your AC blowing warm air or forming ice coils? Learn how to spot gas leakage.",
  },
];

export const HOMEPAGE_FAQS = [
  {
    question: "How do I book a home service on Home-e-Fix?",
    answer: "Simply select your service category, pick a date & time slot, enter your address, and confirm.",
  },
];

export const BOOKING_STATUSES = {
  pending: { label: "Pending", color: "warning" },
  confirmed: { label: "Confirmed", color: "info" },
  assigned: { label: "Assigned", color: "info" },
  in_progress: { label: "In Progress", color: "accent" },
  completed: { label: "Completed", color: "success" },
  cancelled: { label: "Cancelled", color: "error" },
  refunded: { label: "Refunded", color: "muted" },
} as const;

export const OPERATIONAL_CITIES = {
  activeCity: "Kolkata",
  activeHubs: [
    { id: "kolkata-saltlake", name: "Salt Lake & Sector V", pincode: "700091", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-newtown", name: "New Town & Rajarhat", pincode: "700156", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-parkstreet", name: "Park Street & Camac St", pincode: "700016", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-ballygunge", name: "Ballygunge & Gariahat", pincode: "700019", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-alipore", name: "Alipore & New Alipore", pincode: "700027", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-behala", name: "Behala & Thakurpukur", pincode: "700034", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-dumdum", name: "Dum Dum & Lake Town", pincode: "700028", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-tollygunge", name: "Tollygunge & Jadavpur", pincode: "700033", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-howrah", name: "Howrah & Sibpur", pincode: "711101", status: "Active (30-Min Dispatch)" },
  ],
  upcomingCities: [
    { id: "bengaluru", name: "Bengaluru", status: "Launching Q3 2026" },
    { id: "mumbai", name: "Mumbai", status: "Launching Q3 2026" },
    { id: "delhi", name: "Delhi - NCR", status: "Launching Q4 2026" },
    { id: "hyderabad", name: "Hyderabad", status: "Launching Q4 2026" },
    { id: "pune", name: "Pune", status: "Launching Q4 2026" },
  ],
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 12,
  PAGE_SIZE_OPTIONS: [12, 24, 48, 96],
} as const;
