/**
 * Service category definitions matching Phase 3 & 4 specs.
 */
export const SERVICE_CATEGORIES = [
  {
    id: "electrical",
    name: "Electrical",
    slug: "electrical",
    icon: "⚡",
    description: "Wiring, switches, fans, MCB, inverter setup, and electrical repairs",
    color: "#F59E0B",
    count: 40,
    startingPrice: 49,
    estimatedTime: "30-45 mins",
    bannerImage: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=80",
    warranty: "30-Day Service Warranty on all repairs & installations",
  },
  {
    id: "plumbing",
    name: "Plumbing",
    slug: "plumbing",
    icon: "🔧",
    description: "Pipe repairs, tap leaks, bathroom fitting, gully trap, and drainage",
    color: "#3B82F6",
    count: 40,
    startingPrice: 49,
    estimatedTime: "30-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&q=80",
    warranty: "30-Day Free Leakage Re-work Warranty",
  },
  {
    id: "carpentry",
    name: "Carpentry",
    slug: "carpentry",
    icon: "🪚",
    description: "Furniture repair, door locks, hinges, wardrobe assembly, and woodwork",
    color: "#D97706",
    count: 35,
    startingPrice: 249,
    estimatedTime: "45-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&q=80",
    warranty: "30-Day Workmanship Warranty",
  },
  {
    id: "ac",
    name: "AC Services",
    slug: "ac",
    icon: "❄️",
    description: "Foam jet wash, gas refill, installation, noise fix, and maintenance",
    color: "#06B6D4",
    count: 29,
    startingPrice: 499,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80",
    warranty: "90-Day Compressor & Gas Refill Guarantee",
  },
  {
    id: "cleaning",
    name: "Cleaning",
    slug: "cleaning",
    icon: "🧹",
    description: "Full home, kitchen, sofa shampooing, bathroom, and balcony cleaning",
    color: "#10B981",
    count: 50,
    startingPrice: 399,
    estimatedTime: "2-4 hours",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "Satisfaction Re-cleaning Guarantee within 24h",
  },
  {
    id: "painting",
    name: "Painting",
    slug: "painting",
    icon: "🎨",
    description: "Interior, exterior, waterproofing, texture paint, and damp treatment",
    color: "#8B5CF6",
    count: 24,
    startingPrice: 999,
    estimatedTime: "1-3 days",
    bannerImage: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&q=80",
    warranty: "1-Year Peeling & Damp Treatment Warranty",
  },
  {
    id: "civil",
    name: "Civil Repairs",
    slug: "civil",
    icon: "🏗️",
    description: "Tile fixing, wall plastering, concrete repairs, and masonry work",
    color: "#64748B",
    count: 18,
    startingPrice: 499,
    estimatedTime: "2-6 hours",
    bannerImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80",
    warranty: "6-Month Structural Integrity Warranty",
  },
  {
    id: "false-ceiling",
    name: "False Ceiling",
    slug: "false-ceiling",
    icon: "🪵",
    description: "POP, Gypsum board ceiling design, cove lighting, and repair",
    color: "#EAB308",
    count: 14,
    startingPrice: 1499,
    estimatedTime: "1-2 days",
    bannerImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80",
    warranty: "2-Year Anti-Sagging Warranty",
  },
  {
    id: "flooring",
    name: "Flooring & Tiling",
    slug: "flooring",
    icon: "🧱",
    description: "Tile replacement, marble polishing, skirting, and grout sealing",
    color: "#B45309",
    count: 19,
    startingPrice: 899,
    estimatedTime: "3-8 hours",
    bannerImage: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&q=80",
    warranty: "1-Year Grouting & Polish Warranty",
  },
  {
    id: "glass",
    name: "Glass Work",
    slug: "glass",
    icon: "🪟",
    description: "Glass door alignment, sliding window mesh, mirror fitting, and frosted film",
    color: "#38BDF8",
    count: 15,
    startingPrice: 299,
    estimatedTime: "30-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80",
    warranty: "30-Day Alignment & Seal Guarantee",
  },
  {
    id: "modular-kitchen",
    name: "Modular Kitchen",
    slug: "modular-kitchen",
    icon: "🍳",
    description: "Tandem box repair, hydraulic lift, chimney service, and counter alignment",
    color: "#EA580C",
    count: 22,
    startingPrice: 399,
    estimatedTime: "1-3 hours",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "90-Day Hardware & Fitting Warranty",
  },
  {
    id: "appliances",
    name: "Appliances",
    slug: "appliances",
    icon: "🔌",
    description: "Washing machine, microwave, refrigerator, geyser, and chimney repair",
    color: "#0284C7",
    count: 34,
    startingPrice: 299,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=1200&q=80",
    warranty: "30-Day Spares & Service Guarantee",
  },
  {
    id: "pest-control",
    name: "Pest Control",
    slug: "pest-control",
    icon: "🐛",
    description: "Cockroach, termite, bed bugs, ant, and mosquito herbal treatment",
    color: "#EF4444",
    count: 27,
    startingPrice: 699,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    warranty: "90-Day Re-treatment Guarantee",
  },
  {
    id: "security",
    name: "CCTV & Security",
    slug: "security",
    icon: "🛡️",
    description: "CCTV camera setup, smart door locks, video doorbell, and intruder alarms",
    color: "#143560",
    count: 16,
    startingPrice: 699,
    estimatedTime: "1-2 hours",
    bannerImage: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=1200&q=80",
    warranty: "1-Year Hardware & Wiring Warranty",
  },
  {
    id: "smart-home",
    name: "Smart Home",
    slug: "smart-home",
    icon: "🏠",
    description: "Smart switches, Alexa/Google Home voice automation, and WiFi mesh",
    color: "#A855F7",
    count: 20,
    startingPrice: 599,
    estimatedTime: "1-2 hours",
    bannerImage: "https://images.unsplash.com/photo-1558002038-1055907df827?w=1200&q=80",
    warranty: "1-Year Automation Config Support",
  },
  {
    id: "interior-repair",
    name: "Interior Repair",
    slug: "interior-repair",
    icon: "🔨",
    description: "Wardrobe touch-ups, curtain rod fitting, door adjustments, and shelves",
    color: "#EC4899",
    count: 31,
    startingPrice: 349,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "90-Day Hardware & Fitting Warranty",
  },
  {
    id: "inspection",
    name: "Home Inspection",
    slug: "inspection",
    icon: "🔍",
    description: "Pre-purchase home audit, electrical thermal check, and damp scan",
    color: "#2563EB",
    count: 12,
    startingPrice: 1499,
    estimatedTime: "2-3 hours",
    bannerImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80",
    warranty: "Comprehensive 50-Point Audit Report Included",
  },
] as const;

/* ─── Standard Rate Card Policies & Guarantees ─── */

export const RATE_CARD_POLICIES = {
  visitingFee: {
    standard: 49,
    range: "₹49 – ₹99",
    waiver: "Completely waived if you accept the service quote and proceed with the job",
    cancellation: "₹49–₹99 applies only if professional visits and you decide not to proceed (+ 18% GST)",
  },
  serviceWarranty: {
    standardDays: 30,
    label: "30-Day Service Warranty",
    description: "Workmanship re-work guarantee included on all services booked through official app",
  },
  taxation: {
    gstPercent: 18,
    formula: "18% GST Extra (Calculated on labor total)",
  },
  sparesAndMaterials: {
    rule: "Listed prices represent labor charges only. All required material and replacement parts can either be provided by the customer or purchased through the technician as per transparent rate list.",
  },
  nightPeakSurcharge: {
    fee: 150,
    startTime: "8:00 PM",
    description: "Orders scheduled for late evening or night slots (post 8:00 PM) incur an additional flat surcharge of ₹150.",
  },
  finalBillFormula: "Base Labor + 18% GST + Spare Parts (at actuals / transparent rate list)",
} as const;

/* ─── Detailed Services Map by Category ─── */

export const CATEGORY_SERVICES_MAP: Record<string, any[]> = {
  electrical: [
    {
      id: "elec-1",
      name: "Switch/Socket Repair & Replacement",
      slug: "switch-socket-repair-replacement",
      subCategory: "Switch & Socket",
      shortDescription: "Diagnose and fix faulty switches, burnt sockets, or loose electrical contacts.",
      basePrice: 69,
      duration: 30,
      rating: undefined,
      reviewCount: 0,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "Extra at actuals",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-2",
      name: "Plug Replacement (6A / 16A)",
      slug: "plug-replacement",
      subCategory: "Switch & Socket",
      shortDescription: "Replace cracked or burnt 6A or 16A heavy appliance 3-pin plug tops.",
      basePrice: 69,
      duration: 25,
      rating: undefined,
      reviewCount: 0,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&q=80",
      sparesPolicy: "Extra (Plug tops)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-3",
      name: "Full Switchboard Repair / Replacement",
      slug: "full-switchboard-repair",
      subCategory: "Switch & Socket",
      shortDescription: "Complete troubleshooting, modular plate replacement, and rewire of switchboard.",
      basePrice: 149,
      duration: 45,
      rating: undefined,
      reviewCount: 0,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&q=80",
      sparesPolicy: "Extra (Modular plate/board)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-4",
      name: "New Switchbox Installation",
      slug: "new-switchbox-installation",
      subCategory: "Switch & Socket",
      shortDescription: "Chiseling, gangbox fitting, and point connection for new switchboard position.",
      basePrice: 149,
      duration: 45,
      rating: undefined,
      reviewCount: 0,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "Extra (Gangbox & wiring)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-5",
      name: "Fan Regulator Replacement",
      slug: "fan-regulator-replacement",
      subCategory: "Switch & Socket",
      shortDescription: "Replace faulty or hum-producing step/socket fan regulator with genuine unit.",
      basePrice: 79,
      duration: 25,
      rating: undefined,
      reviewCount: 0,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "Extra (Step regulator)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-6",
      name: "Fan Repair (Ceiling/Wall/Exhaust)",
      slug: "fan-repair-all",
      subCategory: "Fan Services",
      shortDescription: "Diagnose slow speed, noise, or capacitor replacement for all types of fans.",
      basePrice: 149,
      duration: 40,
      rating: undefined,
      reviewCount: 0,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      sparesPolicy: "Extra (Capacitor/Winding)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-7",
      name: "Regular Ceiling Fan Installation / Replacement",
      slug: "regular-ceiling-fan-installation",
      subCategory: "Fan Services",
      shortDescription: "Assemble, anchor drill, downrod mount, and wire standard ceiling fan.",
      basePrice: 99,
      discountedPrice: 99,
      duration: 35,
      rating: 4.9,
      reviewCount: 1120,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
      sparesPolicy: "Extra (Downrod/Anchor)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-8",
      name: "Decorative Fan Installation / Replacement",
      slug: "decorative-fan-installation",
      subCategory: "Fan Services",
      shortDescription: "Precision assembly and mounting of decorative underlight blade fans.",
      basePrice: 129,
      discountedPrice: 99,
      duration: 45,
      rating: 4.8,
      reviewCount: 290,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
      sparesPolicy: "Extra (Heavy bracket)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-9",
      name: "Smart / BLDC Ceiling Fan Installation",
      slug: "smart-bldc-fan-installation",
      subCategory: "Fan Services",
      shortDescription: "Installation, PCB pairing, remote kit setup, and BLDC motor testing.",
      basePrice: 129,
      discountedPrice: 99,
      duration: 45,
      rating: 4.9,
      reviewCount: 510,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
      sparesPolicy: "Extra (Remote kit)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-10",
      name: "Wall / Exhaust / Pedestal Fan Installation",
      slug: "wall-exhaust-pedestal-fan-installation",
      subCategory: "Fan Services",
      shortDescription: "Secure wall mounting, exhaust duct fitting, and wire plug connection.",
      basePrice: 99,
      discountedPrice: 99,
      duration: 30,
      rating: 4.7,
      reviewCount: 380,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
      sparesPolicy: "Extra (Fasteners/Wire)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-11",
      name: "Bulb & Holder Installation / Replacement",
      slug: "bulb-holder-replacement",
      subCategory: "Lighting",
      shortDescription: "Fix or replace faulty batten/angle lamp holders and ceiling roses.",
      basePrice: 79,
      discountedPrice: 49,
      duration: 20,
      rating: 4.8,
      reviewCount: 890,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Bulb/Holder)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-12",
      name: "Tube Light Installation / Repair",
      slug: "tube-light-installation",
      subCategory: "Lighting",
      shortDescription: "Mounting, wiring, and replacement of LED tube light batten fittings.",
      basePrice: 99,
      discountedPrice: 99,
      duration: 25,
      rating: 4.8,
      reviewCount: 740,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Batten/Tube)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-13",
      name: "Ceiling Light / Spot Light Installation",
      slug: "ceiling-spot-light-installation",
      subCategory: "Lighting",
      shortDescription: "False ceiling circular cutout mounting, driver wiring, and spot test.",
      basePrice: 149,
      discountedPrice: 89,
      duration: 30,
      rating: 4.8,
      reviewCount: 460,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Driver/Panel)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-14",
      name: "Wall Mounted Light / Outdoor Light",
      slug: "wall-mounted-outdoor-light",
      subCategory: "Lighting",
      shortDescription: "Waterproof exterior fixture or interior wall sconce light fitting.",
      basePrice: 129,
      discountedPrice: 99,
      duration: 35,
      rating: 4.7,
      reviewCount: 310,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Fixture/Tape)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-15",
      name: "Fancy Light / Hanging Light Installation",
      slug: "fancy-hanging-light-installation",
      subCategory: "Lighting",
      shortDescription: "Secure ceiling hook installation, chain drop adjustment, and pendant wiring.",
      basePrice: 249,
      discountedPrice: 149,
      duration: 45,
      rating: 4.9,
      reviewCount: 370,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Chain/Hook)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-16",
      name: "Heavy Chandelier Installation / Replacement",
      slug: "heavy-chandelier-installation",
      subCategory: "Lighting",
      shortDescription: "Heavy-duty expansion anchor ceiling bolting, crystal assembly, and circuit balancing.",
      basePrice: 799,
      discountedPrice: 499,
      duration: 75,
      rating: 4.9,
      reviewCount: 220,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Heavy Anchor)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-17",
      name: "Light Installation / Uninstallation (per string <= 12m)",
      slug: "festive-string-light-install",
      subCategory: "Festive Lighting",
      shortDescription: "Hang or safely dismantle decorative LED rice/fairy light strings.",
      basePrice: 124,
      discountedPrice: 99,
      duration: 30,
      rating: 4.8,
      reviewCount: 450,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1514517521153-1be72277b32f?w=600&q=80",
      sparesPolicy: "Extra (Clips/Extension)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-18",
      name: "Balcony Light Installation (Starry / String)",
      slug: "balcony-string-light-install",
      subCategory: "Festive Lighting",
      shortDescription: "Curtain string light or starry net installation on balcony grills and parapets.",
      basePrice: 495,
      discountedPrice: 248,
      duration: 60,
      rating: 4.8,
      reviewCount: 380,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1514517521153-1be72277b32f?w=600&q=80",
      sparesPolicy: "Extra (Zipties/Hooks)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-19",
      name: "Railing Lights (Rope/String) & Mandir/Lantern",
      slug: "railing-mandir-light-install",
      subCategory: "Festive Lighting",
      shortDescription: "Custom rope light outlining for staircases, puja mandirs, and lanterns.",
      basePrice: 495,
      discountedPrice: 124,
      duration: 45,
      rating: 4.9,
      reviewCount: 290,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1514517521153-1be72277b32f?w=600&q=80",
      sparesPolicy: "Extra (Connectors/Clips)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-20",
      name: "New External Wiring with Clips (per 5m)",
      slug: "external-wiring-clips",
      subCategory: "Wiring",
      shortDescription: "Surface wiring routed cleanly along skirting boards with saddle clips.",
      basePrice: 129,
      discountedPrice: 119,
      duration: 40,
      rating: undefined,
      reviewCount: 0,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&q=80",
      sparesPolicy: "Extra (Wire/Clips per m)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Wire",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-21",
      name: "External Wiring with PVC Casing (per 5m)",
      slug: "external-wiring-pvc-casing",
      subCategory: "Wiring",
      shortDescription: "Heavy PVC casing-capping battens with bend fittings and neat wiring.",
      basePrice: 249,
      duration: 50,
      rating: undefined,
      reviewCount: 0,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80",
      sparesPolicy: "Extra (Casing/Bends)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-22",
      name: "New Internal Wiring (per 5m)",
      slug: "internal-wiring-conduit",
      subCategory: "Wiring",
      shortDescription: "Concealed conduit fishing, junction box routing, and copper wire pulling.",
      basePrice: 269,
      duration: 60,
      rating: undefined,
      reviewCount: 0,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "Extra (Conduit/Wire)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Copper",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-23",
      name: "MCB Switch Repair / Replacement",
      slug: "mcb-switch-repair",
      subCategory: "MCB & Mainboard",
      shortDescription: "Replace faulty single/double pole MCB or isolator switch in DB box.",
      basePrice: 149,
      discountedPrice: 149,
      duration: 30,
      rating: 4.8,
      reviewCount: 710,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "Extra (Single/Double MCB)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + MCB",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-24",
      name: "Main Board Repair / Replacement",
      slug: "main-board-repair",
      subCategory: "MCB & Mainboard",
      shortDescription: "Main distribution box overhaul, busbar tightening, and phase load distribution.",
      basePrice: 279,
      discountedPrice: 279,
      duration: 60,
      rating: 4.8,
      reviewCount: 390,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      sparesPolicy: "Extra (DB Box/Busbar)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Board",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-25",
      name: "Submeter Installation",
      slug: "submeter-installation",
      subCategory: "MCB & Mainboard",
      shortDescription: "Single-phase or three-phase digital submeter installation for tenant sub-billing.",
      basePrice: 299,
      discountedPrice: 249,
      duration: 45,
      rating: 4.9,
      reviewCount: 480,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      sparesPolicy: "Extra (Submeter unit)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Meter",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-26",
      name: "Inverter Check-up / Inspection",
      slug: "inverter-checkup-inspection",
      subCategory: "Inverter & Power",
      shortDescription: "Inverter charging cycle test, battery terminal voltage audit, and cut-off check.",
      basePrice: 160,
      discountedPrice: 159,
      duration: 30,
      rating: 4.7,
      reviewCount: 520,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "N/A (Diagnostic)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-27",
      name: "Inverter Servicing (Terminal clean, water top-up)",
      slug: "inverter-servicing-terminal-clean",
      subCategory: "Inverter & Power",
      shortDescription: "Battery terminal desulphation, petroleum jelly coating, and distilled water top-up.",
      basePrice: 249,
      discountedPrice: 249,
      duration: 45,
      rating: 4.9,
      reviewCount: 840,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      sparesPolicy: "Extra (Distilled water)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Water",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-28",
      name: "Inverter Installation / Uninstallation",
      slug: "inverter-installation-uninstallation",
      subCategory: "Inverter & Power",
      shortDescription: "Heavy DC battery cabling, AC bypass switch connection, and power load wiring.",
      basePrice: 499,
      discountedPrice: 485,
      duration: 60,
      rating: 4.9,
      reviewCount: 430,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      sparesPolicy: "Extra (Battery leads/Sockets)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-29",
      name: "Stabiliser Installation",
      slug: "stabiliser-installation",
      subCategory: "Inverter & Power",
      shortDescription: "Wall mounting of AC/refrigerator voltage stabilizer with input/output wiring.",
      basePrice: 179,
      discountedPrice: 149,
      duration: 30,
      rating: 4.8,
      reviewCount: 320,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "Extra (Wall bracket)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-30",
      name: "Regular Doorbell Installation / Replacement",
      slug: "regular-doorbell-installation",
      subCategory: "Doorbell & Safety",
      shortDescription: "Install ding-dong chime bell and weather-resistant door push switch.",
      basePrice: 99,
      discountedPrice: 99,
      duration: 25,
      rating: 4.7,
      reviewCount: 610,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80",
      sparesPolicy: "Extra (Bell/Push switch)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Bell",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-31",
      name: "Video Doorbell / Video Door Phone (VDP)",
      slug: "video-doorbell-vdp-installation",
      subCategory: "Doorbell & Safety",
      shortDescription: "Outdoor camera mounting, indoor display screen wiring, and smartphone WiFi pairing.",
      basePrice: 749,
      discountedPrice: 599,
      duration: 60,
      rating: 4.9,
      reviewCount: 340,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80",
      sparesPolicy: "Extra (Adapter/Chime)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-32",
      name: "Wireless CCTV Camera Installation",
      slug: "wireless-cctv-camera-installation",
      subCategory: "Doorbell & Safety",
      shortDescription: "Wall/ceiling mount, angle tuning, power adapter routing, and app live feed sync.",
      basePrice: 299,
      discountedPrice: 299,
      duration: 45,
      rating: 4.8,
      reviewCount: 420,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
      sparesPolicy: "Extra (Mount/Cable)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-33",
      name: "TV Socket Installation",
      slug: "tv-socket-installation",
      subCategory: "TV & Audio",
      shortDescription: "Modular DTH coaxial cable socket or HDMI faceplate box installation.",
      basePrice: 89,
      discountedPrice: 89,
      duration: 25,
      rating: 4.7,
      reviewCount: 290,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80",
      sparesPolicy: "Extra (Coaxial/HDMI)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Socket",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-34",
      name: "TV Installation / Uninstallation",
      slug: "tv-installation-uninstallation",
      subCategory: "TV & Audio",
      shortDescription: "Precision spirit-level wall bracket drilling, TV hanging, and cable conceal.",
      basePrice: 399,
      discountedPrice: 249,
      duration: 45,
      rating: 4.9,
      reviewCount: 880,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80",
      sparesPolicy: "Extra (Wall bracket)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-35",
      name: "Sound Bar Installation",
      slug: "sound-bar-installation",
      subCategory: "TV & Audio",
      shortDescription: "Soundbar bracket mounting under TV with optical/AUX audio connection.",
      basePrice: 199,
      discountedPrice: 199,
      duration: 30,
      rating: 4.8,
      reviewCount: 310,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80",
      sparesPolicy: "Extra (Clamps/Cable)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-36",
      name: "Home Theatre System Installation",
      slug: "home-theatre-installation",
      subCategory: "TV & Audio",
      shortDescription: "5.1/7.1 speaker perimeter mounting, subwoofer placement, and surround calibration.",
      basePrice: 399,
      discountedPrice: 249,
      duration: 60,
      rating: 4.8,
      reviewCount: 260,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80",
      sparesPolicy: "Extra (Wiring per m)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-37",
      name: "2-Wheeler EV Charger Installation",
      slug: "2-wheeler-ev-charger-installation",
      subCategory: "EV Charger",
      shortDescription: "Dedicated 16A/25A industrial socket, MCB breaker, and e-scooter charger setup.",
      basePrice: 999,
      discountedPrice: 999,
      duration: 60,
      rating: 4.9,
      reviewCount: 340,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&q=80",
      sparesPolicy: "Extra (16A/25A Industrial)",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Wires",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-38",
      name: "4-Wheeler EV Charger Installation",
      slug: "4-wheeler-ev-charger-installation",
      subCategory: "EV Charger",
      shortDescription: "Heavy armoured cable run, 32A/63A breaker box, and AC wallbox fast-charger commissioning.",
      basePrice: 1499,
      discountedPrice: 1499,
      duration: 90,
      rating: 5.0,
      reviewCount: 190,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&q=80",
      sparesPolicy: "Extra (Armoured cable/MCB)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Cable",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-39",
      name: "Karban Airzone Air Purifying Light Installation",
      slug: "karban-airzone-light-installation",
      subCategory: "Special Appliance",
      shortDescription: "Specialized mounting and wiring of air-purifying ceiling light fixtures.",
      basePrice: 399,
      discountedPrice: 399,
      duration: 45,
      rating: 4.8,
      reviewCount: 120,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      sparesPolicy: "Extra (Fittings/Anchors)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-40",
      name: "General Electrician Consultation / Inspection",
      slug: "general-electrician-consultation",
      subCategory: "Consultation",
      shortDescription: "On-site electrical diagnosis, safety audit, and transparent quote estimate. Visiting charge waived on job acceptance.",
      basePrice: 49,
      discountedPrice: 49,
      duration: 30,
      rating: 4.9,
      reviewCount: 1850,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      sparesPolicy: "N/A (Quote/Inspection)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "₹49 + GST",
      category: { slug: "electrical", name: "Electrical" },
    },
  ],
  plumbing: [
    {
      id: "plumb-1",
      name: "Tap Repair / Washer Replacement",
      slug: "tap-repair-washer-replacement",
      subCategory: "Tap & Mixer",
      shortDescription: "Fix dripping bib cock, pillar tap, or replace worn internal brass spindle.",
      basePrice: 99,
      discountedPrice: 79,
      duration: 25,
      rating: 4.8,
      reviewCount: 1450,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Washer/Spindle)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-2",
      name: "Tap Installation / Replacement",
      slug: "tap-installation-replacement",
      subCategory: "Tap & Mixer",
      shortDescription: "Fit new brass/SS bib cock, angle valve, or long body tap with Teflon sealant.",
      basePrice: 129,
      discountedPrice: 99,
      duration: 30,
      rating: 4.8,
      reviewCount: 980,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Tap/Angle cock)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-3",
      name: "Mixer Tap / Diverter Repair",
      slug: "mixer-tap-diverter-repair",
      subCategory: "Tap & Mixer",
      shortDescription: "Dismantle stuck lever, replace ceramic disc cartridge, or fix hot/cold leak.",
      basePrice: 199,
      discountedPrice: 149,
      duration: 45,
      rating: 4.9,
      reviewCount: 720,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Cartridge/Flange)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-4",
      name: "Wall Mixer / Single Lever Diverter Installation",
      slug: "wall-mixer-diverter-installation",
      subCategory: "Tap & Mixer",
      shortDescription: "Precise S-union alignment, wall flange fitting, and high-pressure leak testing.",
      basePrice: 349,
      discountedPrice: 249,
      duration: 60,
      rating: 4.9,
      reviewCount: 460,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Exposed legs/S-union)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-5",
      name: "Flush Tank Repair / Flush Valve Repair",
      slug: "flush-tank-repair",
      subCategory: "Toilet & Flush",
      shortDescription: "Fix overflowing flush tank, faulty float valve, or sticking dual-flush button.",
      basePrice: 179,
      discountedPrice: 129,
      duration: 35,
      rating: 4.8,
      reviewCount: 890,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Syphon/Inlet valve)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-6",
      name: "Flush Tank Replacement / Installation",
      slug: "flush-tank-replacement",
      subCategory: "Toilet & Flush",
      shortDescription: "Wall mounting new PVC cistern tank, inlet ball valve, and flush pipe connect.",
      basePrice: 299,
      discountedPrice: 249,
      duration: 45,
      rating: 4.7,
      reviewCount: 510,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (PVC Cistern box)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Tank",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-7",
      name: "Western Toilet (Commode) Installation",
      slug: "western-toilet-installation",
      subCategory: "Toilet & Flush",
      shortDescription: "Floor anchoring, wax seal ring placement, inlet jet connection, and silicone seal.",
      basePrice: 699,
      discountedPrice: 499,
      duration: 75,
      rating: 4.9,
      reviewCount: 670,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Gasket/Wax ring/Bolts)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-8",
      name: "Indian Toilet Pot Installation",
      slug: "indian-toilet-pot-installation",
      subCategory: "Toilet & Flush",
      shortDescription: "Subfloor bedding, P-trap connection, pan alignment, and cement grouting.",
      basePrice: 899,
      discountedPrice: 699,
      duration: 90,
      rating: 4.8,
      reviewCount: 310,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Cement/Connectors)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-9",
      name: "Health Faucet / Jet Spray Installation / Repair",
      slug: "health-faucet-jet-spray",
      subCategory: "Toilet & Flush",
      shortDescription: "Replace cracked flexible hose, leaking trigger spray gun, or wall hook.",
      basePrice: 99,
      discountedPrice: 79,
      duration: 20,
      rating: 4.9,
      reviewCount: 1620,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Flexible hose/Gun)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Spares",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-10",
      name: "Toilet Seat Cover Replacement",
      slug: "toilet-seat-cover-replacement",
      subCategory: "Toilet & Flush",
      shortDescription: "Assemble and screw adjustable hinge soft-close western commode seat cover.",
      basePrice: 119,
      discountedPrice: 89,
      duration: 20,
      rating: 4.7,
      reviewCount: 440,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Seat cover/Hinge screws)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Cover",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-11",
      name: "Wash Basin Installation / Uninstallation",
      slug: "wash-basin-installation",
      subCategory: "Sink & Basin",
      shortDescription: "Wall bracket drilling with heavy rag bolts, basin level mounting, and waste fitting.",
      basePrice: 399,
      discountedPrice: 299,
      duration: 50,
      rating: 4.8,
      reviewCount: 580,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Rag bolts/Brackets)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-12",
      name: "Kitchen Sink Installation",
      slug: "kitchen-sink-installation",
      subCategory: "Sink & Basin",
      shortDescription: "Granite counter top drop-in or undermount sink fitting, clamp fixing, and silicone.",
      basePrice: 599,
      discountedPrice: 399,
      duration: 60,
      rating: 4.9,
      reviewCount: 490,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Silicone sealant/Clamps)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-13",
      name: "Waste Pipe / Connection Hose Replacement",
      slug: "waste-pipe-hose-replacement",
      subCategory: "Sink & Basin",
      shortDescription: "Install heavy corrugated waste pipe or SS braided hot/cold connection hose.",
      basePrice: 99,
      discountedPrice: 79,
      duration: 25,
      rating: 4.8,
      reviewCount: 830,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Waste pipe/Flexible tube)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-14",
      name: "Sink Coupling / Waste Coupling Replacement",
      slug: "sink-coupling-replacement",
      subCategory: "Sink & Basin",
      shortDescription: "Unscrew jammed coupling, clean drain outlet, and install new brass/SS waste coupling.",
      basePrice: 129,
      discountedPrice: 99,
      duration: 30,
      rating: 4.7,
      reviewCount: 390,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Brass/SS Coupling)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-15",
      name: "Sink / Wash Basin Drainage Blockage Removal",
      slug: "sink-basin-drainage-unclogging",
      subCategory: "Drainage & Blockage",
      shortDescription: "Clear grease, hair, and soap sludge from bottle trap and drain pipe.",
      basePrice: 249,
      discountedPrice: 199,
      duration: 35,
      rating: 4.8,
      reviewCount: 1140,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Drain cleaner chemical)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-16",
      name: "Toilet / Commode Blockage Unclogging",
      slug: "toilet-commode-blockage-unclogging",
      subCategory: "Drainage & Blockage",
      shortDescription: "Manual auger / rotary machine clearing of toilet bowl and P-trap chokes.",
      basePrice: 399,
      discountedPrice: 299,
      duration: 45,
      rating: 4.9,
      reviewCount: 940,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Drain snake/Machine)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-17",
      name: "Bathroom / Floor Drain Clog Unclogging",
      slug: "bathroom-floor-drain-unclogging",
      subCategory: "Drainage & Blockage",
      shortDescription: "Mechanical removal of floor drain blockage, grating cleaning, and flow restore.",
      basePrice: 349,
      discountedPrice: 249,
      duration: 40,
      rating: 4.8,
      reviewCount: 780,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "N/A",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-18",
      name: "Main Pipeline Drainage Unclogging (Heavy Duty)",
      slug: "main-pipeline-drainage-unclogging",
      subCategory: "Drainage & Blockage",
      shortDescription: "High-pressure jetting and heavy snake cable rodding for underground drainage lines.",
      basePrice: 799,
      discountedPrice: 499,
      duration: 75,
      rating: 4.9,
      reviewCount: 420,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Pressure jetting)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-19",
      name: "Overhead Shower Installation / Replacement",
      slug: "overhead-shower-installation",
      subCategory: "Shower & Bath",
      shortDescription: "Remove scaled shower rose, thread shower arm with Teflon, and test spray pattern.",
      basePrice: 119,
      discountedPrice: 89,
      duration: 25,
      rating: 4.8,
      reviewCount: 650,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Shower arm/Rose)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Shower",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-20",
      name: "Hand Shower / Shower Tube Replacement",
      slug: "hand-shower-tube-replacement",
      subCategory: "Shower & Bath",
      shortDescription: "Fit telephone hand shower, flexible hose, and wall mount holder.",
      basePrice: 99,
      discountedPrice: 79,
      duration: 20,
      rating: 4.8,
      reviewCount: 520,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Hand shower hose/Hook)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-21",
      name: "Thermostatic / Multifunction Shower Panel Install",
      slug: "shower-panel-installation",
      subCategory: "Shower & Bath",
      shortDescription: "Mount multi-jet panel, hook hot/cold lines, and balance thermostatic pressure.",
      basePrice: 799,
      discountedPrice: 499,
      duration: 75,
      rating: 4.9,
      reviewCount: 280,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Heavy wall anchors)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-22",
      name: "Water Tank Cleaning (Up to 1000L)",
      slug: "water-tank-cleaning-1000l",
      subCategory: "Water Tank & Pump",
      shortDescription: "Sludge de-watering, high-pressure tank scrubbing, anti-bacterial wash, and UV scan.",
      basePrice: 699,
      discountedPrice: 499,
      duration: 60,
      rating: 4.9,
      reviewCount: 1120,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "N/A (Cleaning chemical)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-23",
      name: "Overhead Tank Float Valve (Ball Cock) Repair",
      slug: "overhead-tank-float-valve-repair",
      subCategory: "Water Tank & Pump",
      shortDescription: "Replace sticking float valve ball cock to prevent rooftop water overflow.",
      basePrice: 199,
      discountedPrice: 149,
      duration: 35,
      rating: 4.7,
      reviewCount: 460,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "Extra (Brass/PVC float valve)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Valve",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-24",
      name: "Water Pump Installation (Monoblock / Submersible)",
      slug: "water-pump-installation",
      subCategory: "Water Tank & Pump",
      shortDescription: "Rigid foundation bolting, suction foot valve check, union joint pipe fitting.",
      basePrice: 799,
      discountedPrice: 499,
      duration: 75,
      rating: 4.8,
      reviewCount: 390,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "Extra (Foot valve/Union joint)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-25",
      name: "Pressure Booster Pump Installation",
      slug: "pressure-booster-pump-installation",
      subCategory: "Water Tank & Pump",
      shortDescription: "Install pressure booster pump with non-return valve and inline vibration dampers.",
      basePrice: 999,
      discountedPrice: 699,
      duration: 90,
      rating: 4.9,
      reviewCount: 210,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "Extra (NVR valve/Flexible hose)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-26",
      name: "Automatic Water Level Controller Installation",
      slug: "automatic-water-level-controller",
      subCategory: "Water Tank & Pump",
      shortDescription: "Overhead and sump sensor wire installation with automatic relay controller.",
      basePrice: 399,
      discountedPrice: 299,
      duration: 60,
      rating: 4.9,
      reviewCount: 680,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "Extra (Sensor cables/Float switch)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-27",
      name: "Water Heater / Geyser Installation",
      slug: "water-heater-geyser-installation",
      subCategory: "Geyser & Water Heater",
      shortDescription: "Heavy anchor drilling, geyser hanging, flexible connector hookup, and safety valve check.",
      basePrice: 399,
      discountedPrice: 299,
      duration: 50,
      rating: 4.9,
      reviewCount: 1350,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "Extra (Connectors/Angle cock)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-28",
      name: "Geyser Uninstallation",
      slug: "geyser-uninstallation",
      subCategory: "Geyser & Water Heater",
      shortDescription: "Drain geyser water, safely disconnect inlet/outlet pipes, and unmount from wall.",
      basePrice: 249,
      discountedPrice: 199,
      duration: 35,
      rating: 4.8,
      reviewCount: 410,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      sparesPolicy: "N/A",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-29",
      name: "Pipeline Leakage Repair (Exposed Pipe)",
      slug: "pipeline-leakage-repair-exposed",
      subCategory: "Pipeline & Leakage",
      shortDescription: "Cut damaged section, solvent weld CPVC/UPVC coupling or elbow, and pressure test.",
      basePrice: 249,
      discountedPrice: 149,
      duration: 40,
      rating: 4.8,
      reviewCount: 890,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (CPVC/PVC pipe/Elbows)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-30",
      name: "Concealed Wall Pipeline Repair / Replacement",
      slug: "concealed-pipeline-repair",
      subCategory: "Pipeline & Leakage",
      shortDescription: "Trace damp spot, targeted wall plaster chiseling, pipe repair, and leak verification.",
      basePrice: 599,
      discountedPrice: 399,
      duration: 75,
      rating: 4.9,
      reviewCount: 560,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Wall chiseling/CPVC)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-31",
      name: "Water Meter Installation",
      slug: "water-meter-installation",
      subCategory: "Pipeline & Leakage",
      shortDescription: "Cut pipeline, install brass union joints, and mount calibrated water flow meter.",
      basePrice: 299,
      discountedPrice: 249,
      duration: 45,
      rating: 4.7,
      reviewCount: 230,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Water meter unit/Unions)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Meter",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-32",
      name: "Main Valve / Gate Valve Replacement",
      slug: "main-gate-valve-replacement",
      subCategory: "Pipeline & Leakage",
      shortDescription: "Replace corroded or stuck brass ball valve / gate valve at main building header.",
      basePrice: 249,
      discountedPrice: 199,
      duration: 40,
      rating: 4.8,
      reviewCount: 440,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Brass/CPVC Gate valve)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Valve",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-33",
      name: "Washing Machine Water Inlet / Drain Setup",
      slug: "washing-machine-plumbing-setup",
      subCategory: "Appliance Connections",
      shortDescription: "Connect quick-lock tap adapter, extension inlet pipe, and route drain discharge.",
      basePrice: 169,
      discountedPrice: 129,
      duration: 30,
      rating: 4.8,
      reviewCount: 790,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80",
      sparesPolicy: "Extra (Tap adapter/Drain pipe)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-34",
      name: "Water Purifier (RO) Inlet Plumbing Point Setup",
      slug: "water-purifier-inlet-setup",
      subCategory: "Appliance Connections",
      shortDescription: "Install 3-way diverter valve on sink water line and 1/4\" food-grade feed tube.",
      basePrice: 169,
      discountedPrice: 129,
      duration: 30,
      rating: 4.8,
      reviewCount: 650,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Diverter valve/3-way)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Parts",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-35",
      name: "Towel Rail / Soap Dish / Mirror Installation (per item)",
      slug: "towel-rail-mirror-installation",
      subCategory: "Bath Accessories",
      shortDescription: "Precision tile drilling, wall plug anchoring, and level fitting of bath accessories.",
      basePrice: 99,
      discountedPrice: 79,
      duration: 25,
      rating: 4.8,
      reviewCount: 910,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Wall plugs/Anchors)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-36",
      name: "Full Bathroom Accessories Kit Set Installation",
      slug: "full-bathroom-accessories-kit",
      subCategory: "Bath Accessories",
      shortDescription: "Complete 5-to-7 piece hardware set installation: towel rod, ring, tumbler, soap dish, shelves.",
      basePrice: 399,
      discountedPrice: 299,
      duration: 60,
      rating: 4.9,
      reviewCount: 470,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Mounting hardware)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-37",
      name: "Bathroom Tile Grouting / Silicone Gap Sealing",
      slug: "bathroom-tile-grouting-silicone",
      subCategory: "Grouting & Sealing",
      shortDescription: "Scrape hollow joints and fill with waterproof epoxy grout or sanitary silicone.",
      basePrice: 399,
      discountedPrice: 249,
      duration: 60,
      rating: 4.8,
      reviewCount: 620,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      sparesPolicy: "Extra (Epoxy grout/Silicone tube)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Material",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-38",
      name: "Sink / Commode Gap Waterproof Silicone Sealing",
      slug: "sink-commode-silicone-sealing",
      subCategory: "Grouting & Sealing",
      shortDescription: "Apply anti-fungal mildew-resistant silicone bead around vanity sink or toilet base.",
      basePrice: 199,
      discountedPrice: 149,
      duration: 35,
      rating: 4.8,
      reviewCount: 540,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      sparesPolicy: "Extra (Anti-fungal silicone tube)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Tube",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-39",
      name: "Minor Bathroom Seepage Treatment (Chemical Coating)",
      slug: "minor-bathroom-seepage-treatment",
      subCategory: "Waterproofing",
      shortDescription: "Tile joint chemical penetration barrier coating to arrest floor water seepage.",
      basePrice: 799,
      discountedPrice: 499,
      duration: 90,
      rating: 4.9,
      reviewCount: 380,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "Extra (Waterproofing chemical)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "Base + GST + Chemical",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-40",
      name: "General Plumber Inspection / Consultation",
      slug: "general-plumber-consultation",
      subCategory: "Consultation",
      shortDescription: "On-site plumbing diagnostic inspection, pressure assessment, and itemized quote. Visiting charge waived on job acceptance.",
      basePrice: 49,
      discountedPrice: 49,
      duration: 30,
      rating: 4.9,
      reviewCount: 2150,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      sparesPolicy: "N/A (Quote/Inspection)",
      damageCoverage: "Up to ₹10,000",
      visitingCharge: "Waived if service availed",
      finalBillFormula: "₹49 + GST",
      category: { slug: "plumbing", name: "Plumbing" },
    },
  ],
  ac: [
    {
      id: "ac-1",
      name: "Split AC Foam Jet Deep Servicing",
      slug: "split-ac-foam-servicing",
      shortDescription: "High-pressure foam jet wash of cooling coils, blower, tray, and outdoor unit.",
      basePrice: 699,
      discountedPrice: 499,
      duration: 45,
      rating: 4.9,
      reviewCount: 2100,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
    {
      id: "ac-2",
      name: "AC Gas Leakage Check & Top-Up (R32/R410)",
      slug: "ac-gas-leakage-topup",
      shortDescription: "Nitrogen testing, brazing copper pipe leak, vacuuming, and eco refrigerant fill.",
      basePrice: 2499,
      discountedPrice: 1899,
      duration: 90,
      rating: 4.8,
      reviewCount: 1450,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
    {
      id: "ac-3",
      name: "Split AC Un-installation & Re-installation",
      slug: "split-ac-installation",
      shortDescription: "Safe refrigerant recovery, wall bracket mounting, copper piping & testing.",
      basePrice: 1799,
      discountedPrice: 1399,
      duration: 120,
      rating: 4.7,
      reviewCount: 890,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
  ],
  carpentry: [
    {
      id: "carp-1",
      name: "Door Lock & Handle Fitting",
      slug: "door-lock-fitting",
      shortDescription: "Installation of mortise lock, door latch, hinges, and alignment.",
      basePrice: 449,
      discountedPrice: 299,
      duration: 45,
      rating: 4.8,
      reviewCount: 610,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      category: { slug: "carpentry", name: "Carpentry" },
    },
    {
      id: "carp-2",
      name: "Furniture Assembly (IKEA / Wooden)",
      slug: "furniture-assembly",
      shortDescription: "Professional assembly of wardrobes, beds, TV units, and study tables.",
      basePrice: 799,
      discountedPrice: 549,
      duration: 90,
      rating: 4.9,
      reviewCount: 780,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&q=80",
      category: { slug: "carpentry", name: "Carpentry" },
    },
  ],
  cleaning: [
    {
      id: "clean-1",
      name: "Full House Deep Cleaning (2 BHK)",
      slug: "full-house-deep-cleaning",
      shortDescription: "Includes kitchen degreasing, bathroom descaling, balcony wash, and floor buffing.",
      basePrice: 3999,
      discountedPrice: 2999,
      duration: 240,
      rating: 4.9,
      reviewCount: 1800,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
      category: { slug: "cleaning", name: "Deep Cleaning" },
    },
    {
      id: "clean-2",
      name: "3-Seater Sofa Shampoo & Extraction",
      slug: "sofa-shampoo-cleaning",
      shortDescription: "Deep foam shampooing and vacuum moisture extraction for fabric sofas.",
      basePrice: 1199,
      discountedPrice: 899,
      duration: 90,
      rating: 4.8,
      reviewCount: 950,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
      category: { slug: "cleaning", name: "Deep Cleaning" },
    },
  ],
  painting: [
    {
      id: "paint-1",
      name: "Full Home Wall Painting & Putty",
      slug: "full-home-wall-painting",
      shortDescription: "Asian Paints premium emulsion, double coat putty, primer & dust-free sanding.",
      basePrice: 8999,
      discountedPrice: 6999,
      duration: 1440,
      rating: 4.9,
      reviewCount: 720,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&q=80",
      category: { slug: "painting", name: "Painting" },
    },
    {
      id: "paint-2",
      name: "Waterproofing & Wall Damp Treatment",
      slug: "waterproofing-damp-treatment",
      shortDescription: "Doctor Fixit waterproofing, damp lock primer, and wall seepage repair.",
      basePrice: 2499,
      discountedPrice: 1899,
      duration: 180,
      rating: 4.8,
      reviewCount: 510,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&q=80",
      category: { slug: "painting", name: "Painting" },
    },
  ],
  civil: [
    {
      id: "civil-1",
      name: "Tile Replacement & Grouting Repair",
      slug: "tile-replacement-grouting",
      shortDescription: "Fix broken floor/wall tiles, epoxy grouting, and anti-skid bathroom tiling.",
      basePrice: 899,
      discountedPrice: 649,
      duration: 120,
      rating: 4.7,
      reviewCount: 380,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80",
      category: { slug: "civil", name: "Civil & Masonry" },
    },
  ],
  inspection: [
    {
      id: "insp-1",
      name: "Full Home Pre-Purchase Inspection",
      slug: "full-home-inspection",
      shortDescription: "50-point thermal audit for dampness, electrical hazards, and structural cracks.",
      basePrice: 1999,
      discountedPrice: 1499,
      duration: 180,
      rating: 4.9,
      reviewCount: 290,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80",
      category: { slug: "inspection", name: "Home Inspection" },
    },
  ],
  security: [
    {
      id: "sec-1",
      name: "CCTV Camera Installation & Wiring",
      slug: "cctv-camera-installation",
      shortDescription: "HD dome/bullet CCTV camera mounting, DVR configuration & mobile app sync.",
      basePrice: 999,
      discountedPrice: 699,
      duration: 90,
      rating: 4.9,
      reviewCount: 640,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
      category: { slug: "security", name: "Security & CCTV" },
    },
  ],
  glass: [
    {
      id: "glass-1",
      name: "Sliding Window Glass & Mesh Fitting",
      slug: "sliding-window-glass-mesh",
      shortDescription: "Mosquito mesh sliding track fitting, toughened glass replacement, and rollers.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 420,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
      category: { slug: "glass", name: "Glass & Windows" },
    },
  ],
  "smart-home": [
    {
      id: "smart-1",
      name: "Smart Switch & Voice Automation Setup",
      slug: "smart-switch-voice-automation",
      shortDescription: "Convert existing switchboards to Alexa/Google Home smart app control.",
      basePrice: 899,
      discountedPrice: 599,
      duration: 60,
      rating: 4.9,
      reviewCount: 510,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80",
      category: { slug: "smart-home", name: "Smart Home" },
    },
  ],
  "pest-control": [
    {
      id: "pest-1",
      name: "Herbal Cockroach & Ant Control",
      slug: "herbal-cockroach-ant-control",
      shortDescription: "Odorless gel baiting & eco spray treatment with 90-day protection guarantee.",
      basePrice: 899,
      discountedPrice: 699,
      duration: 60,
      rating: 4.8,
      reviewCount: 1120,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      category: { slug: "pest-control", name: "Pest Control" },
    },
  ],
  appliance: [
    {
      id: "app-1",
      name: "Washing Machine Repair & Servicing",
      slug: "washing-machine-repair",
      shortDescription: "Fix spin noise, drum vibration, PCB board, motor, and water inlet valve.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 1350,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80",
      category: { slug: "appliance", name: "Appliance Repair" },
    },
  ],
  marble: [
    {
      id: "marb-1",
      name: "Diamond Italian Marble Polishing",
      slug: "diamond-italian-marble-polishing",
      shortDescription: "Multi-stage diamond pad floor grinding, mirror shine crystallization, and sealant.",
      basePrice: 1499,
      discountedPrice: 999,
      duration: 240,
      rating: 4.9,
      reviewCount: 390,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=600&q=80",
      category: { slug: "marble", name: "Marble Polishing" },
    },
  ],
  "interior-repair": [
    {
      id: "int-1",
      name: "Modular Kitchen Cabinet & Drawer Repair",
      slug: "modular-kitchen-cabinet-repair",
      shortDescription: "Hydraulic hinge replacement, soft-close channel alignment, and drawer repair.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 580,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
      category: { slug: "interior-repair", name: "Interior Repair" },
    },
  ],
};

/* ─── Category Technicians Map ─── */

export const CATEGORY_TECHNICIANS_MAP: Record<string, any[]> = {
  electrical: [
    {
      id: "tech-1",
      displayName: "Suresh Reddy",
      avatar: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&q=80",
      status: "available",
      experience: 7,
      rating: 4.9,
      reviewCount: 340,
      completedJobs: 620,
      serviceRadius: 8,
      specializations: ["Switchboards", "MCB Wiring", "Inverter Setup"],
      verificationStatus: "verified",
    },
    {
      id: "tech-2",
      displayName: "Ramesh Babu",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
      status: "busy",
      experience: 5,
      rating: 4.8,
      reviewCount: 180,
      completedJobs: 390,
      serviceRadius: 12,
      specializations: ["Ceiling Fans", "Chandelier Wiring"],
      verificationStatus: "verified",
    },
  ],
  plumbing: [
    {
      id: "tech-3",
      displayName: "Mahesh Kumar",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
      status: "available",
      experience: 8,
      rating: 4.9,
      reviewCount: 410,
      completedJobs: 850,
      serviceRadius: 6,
      specializations: ["Pipe Leakages", "Bathroom Fittings", "Drain Unclogging"],
      verificationStatus: "verified",
    },
  ],
  ac: [
    {
      id: "tech-4",
      displayName: "Rajesh Varma",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&q=80",
      status: "available",
      experience: 9,
      rating: 4.9,
      reviewCount: 530,
      completedJobs: 1100,
      serviceRadius: 10,
      specializations: ["Foam Jet Washing", "R32 Gas Charging", "Inverter AC"],
      verificationStatus: "verified",
    },
  ],
};

/* ─── Category FAQs Map ─── */

export const CATEGORY_FAQS_MAP: Record<string, any[]> = {
  electrical: [
    {
      question: "Do I need to supply electrical wires or switches?",
      answer: "No, our technician carries high-grade certified wiring, copper switches, and spares. If you already have your own fixtures, we will charge only for installation.",
    },
    {
      question: "Are your electrical repairs covered by a warranty?",
      answer: "Yes! All electrical installations and wiring repairs come with our 30-Day Home-e-Fix Re-work Warranty.",
    },
  ],
  plumbing: [
    {
      question: "What if the leakage starts again after the plumber leaves?",
      answer: "Every plumbing repair is covered by a 30-day leakage warranty. If a leak persists, request a free re-visit via the app, and our senior plumber will fix it.",
    },
  ],
  ac: [
    {
      question: "What is included in Split AC Foam Jet Deep Servicing?",
      answer: "It includes high-pressure foam jet washing of indoor cooling coils, blower wheel, drain tray, air filters, and high-pressure water spray on the outdoor condenser unit.",
    },
    {
      question: "How do I know if my AC requires a gas refill?",
      answer: "Common signs include reduced cooling, ice formation on the indoor unit's copper pipes, or a continuous ticking sound from the compressor.",
    },
  ],
};

/* ─── App Config ─── */

export const APP_CONFIG = {
  name: "Home-e-Fix",
  tagline: "Fixing Homes. Earning Trust.",
  description:
    "Home-e-Fix is your trusted Urban Company–style marketplace for all home services. Book verified professionals for electrical, plumbing, AC, cleaning, painting, and 10+ categories.",
  supportEmail: "support@homeefix.com",
  supportPhone: "+91 1800 123 4567",
  socialLinks: {
    facebook: "https://facebook.com/homeefix",
    instagram: "https://instagram.com/homeefix",
    twitter: "https://twitter.com/homeefix",
    linkedin: "https://linkedin.com/company/homeefix",
    youtube: "https://youtube.com/@homeefix",
  },
  playStoreLink: "#",
  appStoreLink: "#",
} as const;

export interface PopularServiceItem {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  basePrice: number;
  discountedPrice?: number;
  duration: number;
  rating?: number;
  reviewCount: number;
  isPopular: boolean;
  pricingModel: "STARTING_FROM" | "FIXED" | "PER_UNIT" | "RANGE" | "QUOTE" | "INSPECTION_REQUIRED";
  pricingLabel: string;
  pricingDetails: string;
  warranty?: string;
  unit?: string;
  category: { slug: string; name: string };
  thumbnail: string;
}

export const POPULAR_SERVICES: PopularServiceItem[] = [
  {
    id: "pop-ac-clean",
    name: "Split AC Foam Jet Deep Servicing",
    slug: "split-ac-foam-servicing",
    shortDescription: "Complete indoor & outdoor unit foam cleaning with high-pressure jet spray.",
    basePrice: 499,
    duration: 45,
    rating: 4.8,
    reviewCount: 0,
    isPopular: true,
    pricingModel: "STARTING_FROM" as const,
    pricingLabel: "Starting from ₹499",
    pricingDetails: "Complete service labor included • No hidden fee",
    warranty: "90-Day Compressor & Cooling Warranty",
    category: { slug: "ac", name: "AC Services" },
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
  },
  {
    id: "pop-plumb-leak",
    name: "Bathroom Leakage & Tap Fitting",
    slug: "bathroom-leakage-tap-repair",
    shortDescription: "Fix leaking taps, flush valves, diverters, and pipe joints with rework guarantee.",
    basePrice: 199,
    duration: 30,
    rating: 4.9,
    reviewCount: 0,
    isPopular: true,
    pricingModel: "STARTING_FROM" as const,
    pricingLabel: "Starting from ₹199",
    pricingDetails: "Standard repair labour charge • Spares extra at MRP",
    warranty: "30-Day Leakage Rework Warranty",
    category: { slug: "plumbing", name: "Plumbing" },
    thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80",
  },
  {
    id: "pop-elec-mcb",
    name: "Switch & Socket Installation / Repair",
    slug: "switch-socket-installation",
    shortDescription: "Replacement of burnt switches, modular sockets, and MCB trip troubleshooting.",
    basePrice: 149,
    duration: 30,
    rating: 4.7,
    reviewCount: 0,
    isPopular: true,
    pricingModel: "PER_UNIT" as const,
    pricingLabel: "₹149 / point",
    unit: "point",
    pricingDetails: "Installation labour charge • Modular boxes extra if needed",
    warranty: "30-Day Electrical Wiring Warranty",
    category: { slug: "electrical", name: "Electrical" },
    thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80",
  },
  {
    id: "pop-sofa-clean",
    name: "3-Seater Fabric Sofa Shampooing",
    slug: "sofa-shampoo-cleaning",
    shortDescription: "Deep wet-extraction shampooing to remove stubborn stains, allergens & odors.",
    basePrice: 899,
    duration: 90,
    rating: 4.8,
    reviewCount: 0,
    isPopular: true,
    pricingModel: "FIXED" as const,
    pricingLabel: "Fixed ₹899",
    pricingDetails: "Eco-friendly shampoo & mechanized suction included",
    warranty: "Satisfaction Re-cleaning Cover (24h)",
    category: { slug: "cleaning", name: "Cleaning" },
    thumbnail: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80",
  },
  {
    id: "pop-carpentry-repair",
    name: "Furniture Assembly & Woodwork Repair",
    slug: "furniture-assembly-repair",
    shortDescription: "Custom furniture assembly, door hinge alignment, lock replacement, and woodwork.",
    basePrice: 349,
    duration: 60,
    rating: 4.8,
    reviewCount: 0,
    isPopular: true,
    pricingModel: "STARTING_FROM" as const,
    pricingLabel: "Starting from ₹349",
    pricingDetails: "Standard carpentry labor • Hardware fittings extra",
    warranty: "30-Day Workmanship Warranty",
    category: { slug: "carpentry", name: "Carpentry" },
    thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80",
  },
  {
    id: "pop-cctv-install",
    name: "HD CCTV Camera Setup & Installation",
    slug: "cctv-installation",
    shortDescription: "Outdoor/indoor IP & analog camera mounting, wiring, DVR setup, and mobile viewing.",
    basePrice: 599,
    duration: 60,
    rating: 4.9,
    reviewCount: 0,
    isPopular: true,
    pricingModel: "FIXED" as const,
    pricingLabel: "Fixed ₹599",
    pricingDetails: "Camera mounting & wiring configuration included",
    warranty: "30-Day Alignment & Network Warranty",
    category: { slug: "security", name: "Security & CCTV" },
    thumbnail: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80",
  },
];

export const EMERGENCY_SERVICES = [
  {
    id: "emg-burst",
    title: "Major Pipe Burst & Flooding",
    icon: "🚰",
    category: "Plumbing",
    baseInspectionFee: 499,
    description: "Urgent main line shutoff, pressure leakage clamping, and drainage control.",
  },
  {
    id: "emg-power",
    title: "Total Power Blackout / MCB Burnout",
    icon: "⚡",
    category: "Electrical",
    baseInspectionFee: 499,
    description: "Phase short-circuit repair, main breaker trip fix, and emergency wiring.",
  },
  {
    id: "emg-lockout",
    title: "Door Lock Jam / Lockout",
    icon: "🔑",
    category: "Carpentry",
    baseInspectionFee: 499,
    description: "Non-destructive lock opening, mortise cylinder release, and urgent latch repair.",
  },
];

export const WHY_HOMEEFIX = [
  {
    id: "verified-pros",
    icon: "🛡️",
    title: "Verified Professionals",
    description: "Every professional undergoes multi-tier identity verification, police record checks, and practical trade skill assessments.",
    highlight: "100% Background Checked",
  },
  {
    id: "transparent-pricing",
    icon: "💳",
    title: "Transparent Pricing",
    description: "Upfront standard rate cards before service begins. No arbitrary bargaining, hidden transit charges, or surprise extras.",
    highlight: "Standard Rate Cards",
  },
  {
    id: "genuine-materials",
    icon: "⚙️",
    title: "Genuine Materials",
    description: "All replacement parts and spare hardware sourced with manufacturer authenticity, itemized transparently in your digital bill.",
    highlight: "Original Spares",
  },
  {
    id: "service-warranty",
    icon: "✨",
    title: "Service Warranty",
    description: "Every job is backed by a dependable re-work guarantee. If the issue recurs within the warranty window, we fix it free of charge.",
    highlight: "30 to 90 Days Cover",
  },
];

export const OPERATIONAL_PILLARS = [
  {
    id: "digital-invoice",
    title: "Digital Invoice",
    description: "Automated GST-compliant invoices generated directly to your account upon job completion.",
  },
  {
    id: "live-updates",
    title: "Live Booking Updates",
    description: "Real-time dispatch alerts, ETA calculations, and step-by-step service progress notifications.",
  },
  {
    id: "customer-support",
    title: "Customer Support",
    description: "Dedicated support team ready to assist via direct phone hotline and responsive in-app chat.",
  },
  {
    id: "cashless-payment",
    title: "Cashless Payment",
    description: "Pay securely after work inspection via UPI, Debit/Credit Card, Netbanking, or Wallet.",
  },
];

export const HOMEEFIX_GUARANTEE_PILLARS = [
  {
    title: "Verified Professional",
    description: "Assigned technician is background verified with proven trade experience.",
    icon: "🛡️",
  },
  {
    title: "Transparent Pricing",
    description: "Standard upfront rates with itemized labour and spare parts billing.",
    icon: "📋",
  },
  {
    title: "Service Warranty",
    description: "Free re-visit and re-work guarantee across all eligible maintenance jobs.",
    icon: "✨",
  },
  {
    title: "Digital Invoice",
    description: "Instantly accessible GST tax invoices stored safely in your customer dashboard.",
    icon: "🧾",
  },
  {
    title: "Dedicated Support",
    description: "Direct assistance through our helpline and resolution support team.",
    icon: "🎧",
  },
];

export const TESTIMONIALS = [
  {
    userName: "Siddhartha Roy",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80",
    rating: 5,
    date: "August 2026",
    comment: "The AC foam deep cleaning was extremely thorough. The technician showed up on time, cleaned the indoor and outdoor units, and the airflow restored immediately. Clear digital invoice sent right after payment.",
    serviceName: "Split AC Foam Jet Servicing",
    isVerified: true,
    helpfulCount: 34,
  },
  {
    userName: "Ananya Banerjee",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    rating: 5,
    date: "August 2026",
    comment: "Had an urgent bathroom pipe leak in Salt Lake. The plumber arrived with all the necessary copper fittings, replaced the cracked joint, and tested pressure thoroughly. Very professional experience.",
    serviceName: "Bathroom Leakage Repair",
    isVerified: true,
    helpfulCount: 29,
  },
  {
    userName: "Vikram Sen",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    rating: 5,
    date: "July 2026",
    comment: "Booked switchboard replacement and MCB diagnosis. Transparent rate card, no bargaining, and payment via UPI only after checking all light points. Will book again.",
    serviceName: "Switch & Socket Installation",
    isVerified: true,
    helpfulCount: 18,
  },
];

export const MEMBERSHIP_PLANS = {
  monthly: {
    id: "plus-monthly",
    name: "Monthly Pass",
    price: 99,
    period: "month",
    periodLabel: "/mo",
    billingCycle: "Billed monthly",
    discountPercent: 10,
    perks: [
      "Priority technician assignment",
      "10% discount on labour rates",
      "Standard 45-day warranty",
      "Cancel anytime with 1 click",
    ],
  },
  annual: {
    id: "plus-annual",
    name: "Annual PLUS",
    price: 999,
    period: "year",
    periodLabel: "/yr",
    billingCycle: "₹999 billed annually",
    discountPercent: 20,
    perks: [
      "20% discount on technician labour",
      "Waived platform & safety fees",
      "Priority dispatch queue",
      "Extended 60-day rework warranty",
      "Annual home health audit check",
    ],
  },
} as const;

export const BLOG_ARTICLES = [
  {
    id: "blog-ac-maintenance",
    title: "5 Essential Signs Your AC Requires Foam Deep Jet Cleaning",
    category: "AC Care",
    date: "August 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1614359835514-92f8ba196357?w=600&q=80",
    snippet: "Is your cooling reduced or is moisture dripping from the vents? Learn how regular deep servicing improves air quality and compressor life.",
  },
  {
    id: "blog-monsoon-plumbing",
    title: "Monsoon Home Checklist: Preventing Pipe Clogs & Wall Dampness",
    category: "Plumbing & Civil",
    date: "July 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
    snippet: "High humidity and heavy rains can cause drain backups and wall seepage. Here are 4 key preventative checks every homeowner should perform.",
  },
  {
    id: "blog-electrical-safety",
    title: "Understanding MCB Trips & Surge Protection for Modern Homes",
    category: "Electrical Safety",
    date: "June 2026",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=600&q=80",
    snippet: "Frequent breaker trips indicate overloaded phases or neutral faults. Discover how timely circuit repair protects expensive electronic appliances.",
  },
];

export const HOMEPAGE_FAQS = [
  {
    question: "How does Home-e-Fix work?",
    answer: "Select your desired home service, pick your preferred date and time slot, and confirm your address. A verified professional is assigned to your booking, arrives with tools and materials, completes the work to high standards, and you pay securely after inspecting the job.",
  },
  {
    question: "Are professionals background verified?",
    answer: "Yes. Every professional on Home-e-Fix undergoes a rigorous onboarding workflow including government ID verification (Aadhaar & PAN), police verification checks, and practical trade skill assessments.",
  },
  {
    question: "What does the service price include?",
    answer: "Our standard prices cover professional labour charges and standard diagnostic assessment. If replacement spare parts or raw materials are required, the technician provides upfront cost estimates based on our standard transparent rate card before installing.",
  },
  {
    question: "Can I reschedule my booking?",
    answer: "Yes, you can easily reschedule your booking directly from your customer dashboard or by contacting support before the technician is dispatched, free of charge.",
  },
  {
    question: "How does cancellation work?",
    answer: "Bookings can be cancelled free of charge prior to technician dispatch. If a cancellation is requested after a technician has arrived on-site, a standard minimum inspection fee applies to compensate the professional for travel and time.",
  },
  {
    question: "What happens if additional materials are required?",
    answer: "Our technician will inspect the requirements on-site and inform you of the necessary parts and prices beforehand. You can either provide the materials yourself or authorize the technician to procure genuine OEM parts with invoice proof.",
  },
  {
    question: "Is there a service warranty?",
    answer: "Yes, most repair and servicing categories include our 30-Day to 90-Day Home-e-Fix Re-work Warranty. If the same issue recurs within the warranty period, we send a technician for a complimentary rework inspection.",
  },
  {
    question: "How do I contact customer support?",
    answer: "Our dedicated support team is available via our toll-free helpline +91 1800 123 4567, email at support@homeefix.com, or through the Help Center in your customer account.",
  },
];

export const BOOKING_STATUSES = {
  pending: { label: "Pending", color: "warning" },
  confirmed: { label: "Confirmed", color: "info" },
  assigned: { label: "Assigned", color: "info" },
  in_progress: { label: "In Progress", color: "accent" },
  completed: { label: "Completed", color: "success" },
  cancelled: { label: "Cancelled", color: "error" },
  refunded: { label: "Refunded", color: "muted" },
} as const;

export const OPERATIONAL_CITIES = {
  activeCity: "Kolkata",
  activeHubs: [
    { id: "kolkata-saltlake", name: "Salt Lake & Sector V", pincode: "700091", status: "Operational" },
    { id: "kolkata-newtown", name: "New Town & Rajarhat", pincode: "700156", status: "Operational" },
    { id: "kolkata-parkstreet", name: "Park Street & Camac St", pincode: "700016", status: "Operational" },
    { id: "kolkata-ballygunge", name: "Ballygunge & Gariahat", pincode: "700019", status: "Operational" },
    { id: "kolkata-alipore", name: "Alipore & New Alipore", pincode: "700027", status: "Operational" },
    { id: "kolkata-behala", name: "Behala & Thakurpukur", pincode: "700034", status: "Operational" },
    { id: "kolkata-dumdum", name: "Dum Dum & Lake Town", pincode: "700028", status: "Operational" },
    { id: "kolkata-tollygunge", name: "Tollygunge & Jadavpur", pincode: "700033", status: "Operational" },
    { id: "kolkata-howrah", name: "Howrah & Sibpur", pincode: "711101", status: "Operational" },
  ],
  upcomingCities: [
    { id: "bengaluru", name: "Bengaluru", status: "Launching Q3 2026" },
    { id: "mumbai", name: "Mumbai", status: "Launching Q3 2026" },
    { id: "delhi", name: "Delhi - NCR", status: "Launching Q4 2026" },
    { id: "hyderabad", name: "Hyderabad", status: "Launching Q4 2026" },
    { id: "pune", name: "Pune", status: "Launching Q4 2026" },
  ],
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 12,
  PAGE_SIZE_OPTIONS: [12, 24, 48, 96],
} as const;
