/**
 * Service category definitions matching Phase 3 & 4 specs.
 */
export const SERVICE_CATEGORIES = [
  {
    id: "electrical",
    name: "Electrical",
    slug: "electrical",
    icon: "⚡",
    description: "Wiring, switches, fans, MCB, inverter setup, and electrical repairs",
    color: "#F59E0B",
    count: 42,
    startingPrice: 149,
    estimatedTime: "30-45 mins",
    bannerImage: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=80",
    warranty: "30-Day Service Warranty on all repairs & installations",
  },
  {
    id: "plumbing",
    name: "Plumbing",
    slug: "plumbing",
    icon: "🔧",
    description: "Pipe repairs, tap leaks, bathroom fitting, gully trap, and drainage",
    color: "#3B82F6",
    count: 38,
    startingPrice: 199,
    estimatedTime: "30-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&q=80",
    warranty: "30-Day Free Leakage Re-work Warranty",
  },
  {
    id: "carpentry",
    name: "Carpentry",
    slug: "carpentry",
    icon: "🪚",
    description: "Furniture repair, door locks, hinges, wardrobe assembly, and woodwork",
    color: "#D97706",
    count: 35,
    startingPrice: 249,
    estimatedTime: "45-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&q=80",
    warranty: "30-Day Workmanship Warranty",
  },
  {
    id: "ac",
    name: "AC Services",
    slug: "ac",
    icon: "❄️",
    description: "Foam jet wash, gas refill, installation, noise fix, and maintenance",
    color: "#06B6D4",
    count: 29,
    startingPrice: 499,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&q=80",
    warranty: "90-Day Compressor & Gas Refill Guarantee",
  },
  {
    id: "cleaning",
    name: "Cleaning",
    slug: "cleaning",
    icon: "🧹",
    description: "Full home, kitchen, sofa shampooing, bathroom, and balcony cleaning",
    color: "#10B981",
    count: 50,
    startingPrice: 399,
    estimatedTime: "2-4 hours",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "Satisfaction Re-cleaning Guarantee within 24h",
  },
  {
    id: "painting",
    name: "Painting",
    slug: "painting",
    icon: "🎨",
    description: "Interior, exterior, waterproofing, texture paint, and damp treatment",
    color: "#8B5CF6",
    count: 24,
    startingPrice: 999,
    estimatedTime: "1-3 days",
    bannerImage: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1200&q=80",
    warranty: "1-Year Peeling & Damp Treatment Warranty",
  },
  {
    id: "civil",
    name: "Civil Repairs",
    slug: "civil",
    icon: "🏗️",
    description: "Tile fixing, wall plastering, concrete repairs, and masonry work",
    color: "#64748B",
    count: 18,
    startingPrice: 499,
    estimatedTime: "2-6 hours",
    bannerImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80",
    warranty: "6-Month Structural Integrity Warranty",
  },
  {
    id: "false-ceiling",
    name: "False Ceiling",
    slug: "false-ceiling",
    icon: "🪵",
    description: "POP, Gypsum board ceiling design, cove lighting, and repair",
    color: "#EAB308",
    count: 14,
    startingPrice: 1499,
    estimatedTime: "1-2 days",
    bannerImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80",
    warranty: "2-Year Anti-Sagging Warranty",
  },
  {
    id: "flooring",
    name: "Flooring & Tiling",
    slug: "flooring",
    icon: "🧱",
    description: "Tile replacement, marble polishing, skirting, and grout sealing",
    color: "#B45309",
    count: 19,
    startingPrice: 899,
    estimatedTime: "3-8 hours",
    bannerImage: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=1200&q=80",
    warranty: "1-Year Grouting & Polish Warranty",
  },
  {
    id: "glass",
    name: "Glass Work",
    slug: "glass",
    icon: "🪟",
    description: "Glass door alignment, sliding window mesh, mirror fitting, and frosted film",
    color: "#38BDF8",
    count: 15,
    startingPrice: 299,
    estimatedTime: "30-60 mins",
    bannerImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80",
    warranty: "30-Day Alignment & Seal Guarantee",
  },
  {
    id: "modular-kitchen",
    name: "Modular Kitchen",
    slug: "modular-kitchen",
    icon: "🍳",
    description: "Tandem box repair, hydraulic lift, chimney service, and counter alignment",
    color: "#EA580C",
    count: 22,
    startingPrice: 399,
    estimatedTime: "1-3 hours",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "90-Day Hardware & Fitting Warranty",
  },
  {
    id: "appliances",
    name: "Appliances",
    slug: "appliances",
    icon: "🔌",
    description: "Washing machine, microwave, refrigerator, geyser, and chimney repair",
    color: "#0284C7",
    count: 34,
    startingPrice: 299,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=1200&q=80",
    warranty: "30-Day Spares & Service Guarantee",
  },
  {
    id: "pest-control",
    name: "Pest Control",
    slug: "pest-control",
    icon: "🐛",
    description: "Cockroach, termite, bed bugs, ant, and mosquito herbal treatment",
    color: "#EF4444",
    count: 27,
    startingPrice: 699,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    warranty: "90-Day Re-treatment Guarantee",
  },
  {
    id: "security",
    name: "CCTV & Security",
    slug: "security",
    icon: "🛡️",
    description: "CCTV camera setup, smart door locks, video doorbell, and intruder alarms",
    color: "#143560",
    count: 16,
    startingPrice: 699,
    estimatedTime: "1-2 hours",
    bannerImage: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=1200&q=80",
    warranty: "1-Year Hardware & Wiring Warranty",
  },
  {
    id: "smart-home",
    name: "Smart Home",
    slug: "smart-home",
    icon: "🏠",
    description: "Smart switches, Alexa/Google Home voice automation, and WiFi mesh",
    color: "#A855F7",
    count: 20,
    startingPrice: 599,
    estimatedTime: "1-2 hours",
    bannerImage: "https://images.unsplash.com/photo-1558002038-1055907df827?w=1200&q=80",
    warranty: "1-Year Automation Config Support",
  },
  {
    id: "interior-repair",
    name: "Interior Repair",
    slug: "interior-repair",
    icon: "🔨",
    description: "Wardrobe touch-ups, curtain rod fitting, door adjustments, and shelves",
    color: "#EC4899",
    count: 31,
    startingPrice: 349,
    estimatedTime: "45-90 mins",
    bannerImage: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&q=80",
    warranty: "90-Day Hardware & Fitting Warranty",
  },
  {
    id: "inspection",
    name: "Home Inspection",
    slug: "inspection",
    icon: "🔍",
    description: "Pre-purchase home audit, electrical thermal check, and damp scan",
    color: "#2563EB",
    count: 12,
    startingPrice: 1499,
    estimatedTime: "2-3 hours",
    bannerImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&q=80",
    warranty: "Comprehensive 50-Point Audit Report Included",
  },
] as const;

/* ─── Detailed Services Map by Category ─── */

export const CATEGORY_SERVICES_MAP: Record<string, any[]> = {
  electrical: [
    {
      id: "elec-1",
      name: "Switch & Socket Repair / Replacement",
      slug: "switch-socket-repair",
      shortDescription: "Fix faulty switches, burnt sockets, or install new modular switchboards.",
      basePrice: 199,
      discountedPrice: 149,
      duration: 30,
      rating: 4.8,
      reviewCount: 920,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-2",
      name: "Ceiling Fan Installation & Repair",
      slug: "ceiling-fan-installation",
      shortDescription: "Assembly, heavy hook mounting, regulator replacement, or noise troubleshooting.",
      basePrice: 299,
      discountedPrice: 199,
      duration: 45,
      rating: 4.9,
      reviewCount: 650,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-3",
      name: "MCB & Fuse Box Circuit Repair",
      slug: "mcb-fuse-box-repair",
      shortDescription: "Troubleshoot frequent MCB trips, neutral short circuits, and phase balancing.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.7,
      reviewCount: 480,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
    {
      id: "elec-4",
      name: "Chandelier & Decorative Light Mounting",
      slug: "chandelier-mounting",
      shortDescription: "Safe ceiling drilling, heavy-duty anchor installation, and electrical wiring.",
      basePrice: 799,
      discountedPrice: 599,
      duration: 60,
      rating: 4.8,
      reviewCount: 310,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
      category: { slug: "electrical", name: "Electrical" },
    },
  ],
  plumbing: [
    {
      id: "plumb-1",
      name: "Tap Leakage & Spout Replacement",
      slug: "tap-leakage-replacement",
      shortDescription: "Fix dripping taps, washer replacement, or install modern mixer taps.",
      basePrice: 299,
      discountedPrice: 199,
      duration: 30,
      rating: 4.9,
      reviewCount: 1250,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-2",
      name: "Drainage & Wash Basin Unclogging",
      slug: "drainage-unclogging",
      shortDescription: "Clear stubborn blockages in wash basins, floor traps, and kitchen sinks.",
      basePrice: 449,
      discountedPrice: 299,
      duration: 45,
      rating: 4.8,
      reviewCount: 880,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-3",
      name: "Flush Tank & Western Toilet Repair",
      slug: "flush-tank-toilet-repair",
      shortDescription: "Fix continuously running flush tanks, syphon kit replacement, or jet spray.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.7,
      reviewCount: 540,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
    {
      id: "plumb-4",
      name: "Water Heater Geyser Connection & Piping",
      slug: "geyser-connection-piping",
      shortDescription: "Connecting hot/cold inlet pipes, pressure release valve, and leak check.",
      basePrice: 599,
      discountedPrice: 449,
      duration: 60,
      rating: 4.9,
      reviewCount: 410,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600&q=80",
      category: { slug: "plumbing", name: "Plumbing" },
    },
  ],
  ac: [
    {
      id: "ac-1",
      name: "Split AC Foam Jet Deep Servicing",
      slug: "split-ac-foam-servicing",
      shortDescription: "High-pressure foam jet wash of cooling coils, blower, tray, and outdoor unit.",
      basePrice: 699,
      discountedPrice: 499,
      duration: 45,
      rating: 4.9,
      reviewCount: 2100,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
    {
      id: "ac-2",
      name: "AC Gas Leakage Check & Top-Up (R32/R410)",
      slug: "ac-gas-leakage-topup",
      shortDescription: "Nitrogen testing, brazing copper pipe leak, vacuuming, and eco refrigerant fill.",
      basePrice: 2499,
      discountedPrice: 1899,
      duration: 90,
      rating: 4.8,
      reviewCount: 1450,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
    {
      id: "ac-3",
      name: "Split AC Un-installation & Re-installation",
      slug: "split-ac-installation",
      shortDescription: "Safe refrigerant recovery, wall bracket mounting, copper piping & testing.",
      basePrice: 1799,
      discountedPrice: 1399,
      duration: 120,
      rating: 4.7,
      reviewCount: 890,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      category: { slug: "ac", name: "AC Repair & Service" },
    },
  ],
  carpentry: [
    {
      id: "carp-1",
      name: "Door Lock & Handle Fitting",
      slug: "door-lock-fitting",
      shortDescription: "Installation of mortise lock, door latch, hinges, and alignment.",
      basePrice: 449,
      discountedPrice: 299,
      duration: 45,
      rating: 4.8,
      reviewCount: 610,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&q=80",
      category: { slug: "carpentry", name: "Carpentry" },
    },
    {
      id: "carp-2",
      name: "Furniture Assembly (IKEA / Wooden)",
      slug: "furniture-assembly",
      shortDescription: "Professional assembly of wardrobes, beds, TV units, and study tables.",
      basePrice: 799,
      discountedPrice: 549,
      duration: 90,
      rating: 4.9,
      reviewCount: 780,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&q=80",
      category: { slug: "carpentry", name: "Carpentry" },
    },
  ],
  cleaning: [
    {
      id: "clean-1",
      name: "Full House Deep Cleaning (2 BHK)",
      slug: "full-house-deep-cleaning",
      shortDescription: "Includes kitchen degreasing, bathroom descaling, balcony wash, and floor buffing.",
      basePrice: 3999,
      discountedPrice: 2999,
      duration: 240,
      rating: 4.9,
      reviewCount: 1800,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
      category: { slug: "cleaning", name: "Deep Cleaning" },
    },
    {
      id: "clean-2",
      name: "3-Seater Sofa Shampoo & Extraction",
      slug: "sofa-shampoo-cleaning",
      shortDescription: "Deep foam shampooing and vacuum moisture extraction for fabric sofas.",
      basePrice: 1199,
      discountedPrice: 899,
      duration: 90,
      rating: 4.8,
      reviewCount: 950,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
      category: { slug: "cleaning", name: "Deep Cleaning" },
    },
  ],
  painting: [
    {
      id: "paint-1",
      name: "Full Home Wall Painting & Putty",
      slug: "full-home-wall-painting",
      shortDescription: "Asian Paints premium emulsion, double coat putty, primer & dust-free sanding.",
      basePrice: 8999,
      discountedPrice: 6999,
      duration: 1440,
      rating: 4.9,
      reviewCount: 720,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&q=80",
      category: { slug: "painting", name: "Painting" },
    },
    {
      id: "paint-2",
      name: "Waterproofing & Wall Damp Treatment",
      slug: "waterproofing-damp-treatment",
      shortDescription: "Doctor Fixit waterproofing, damp lock primer, and wall seepage repair.",
      basePrice: 2499,
      discountedPrice: 1899,
      duration: 180,
      rating: 4.8,
      reviewCount: 510,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&q=80",
      category: { slug: "painting", name: "Painting" },
    },
  ],
  civil: [
    {
      id: "civil-1",
      name: "Tile Replacement & Grouting Repair",
      slug: "tile-replacement-grouting",
      shortDescription: "Fix broken floor/wall tiles, epoxy grouting, and anti-skid bathroom tiling.",
      basePrice: 899,
      discountedPrice: 649,
      duration: 120,
      rating: 4.7,
      reviewCount: 380,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80",
      category: { slug: "civil", name: "Civil & Masonry" },
    },
  ],
  inspection: [
    {
      id: "insp-1",
      name: "Full Home Pre-Purchase Inspection",
      slug: "full-home-inspection",
      shortDescription: "50-point thermal audit for dampness, electrical hazards, and structural cracks.",
      basePrice: 1999,
      discountedPrice: 1499,
      duration: 180,
      rating: 4.9,
      reviewCount: 290,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80",
      category: { slug: "inspection", name: "Home Inspection" },
    },
  ],
  security: [
    {
      id: "sec-1",
      name: "CCTV Camera Installation & Wiring",
      slug: "cctv-camera-installation",
      shortDescription: "HD dome/bullet CCTV camera mounting, DVR configuration & mobile app sync.",
      basePrice: 999,
      discountedPrice: 699,
      duration: 90,
      rating: 4.9,
      reviewCount: 640,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
      category: { slug: "security", name: "Security & CCTV" },
    },
  ],
  glass: [
    {
      id: "glass-1",
      name: "Sliding Window Glass & Mesh Fitting",
      slug: "sliding-window-glass-mesh",
      shortDescription: "Mosquito mesh sliding track fitting, toughened glass replacement, and rollers.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 420,
      isPopular: false,
      thumbnail: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
      category: { slug: "glass", name: "Glass & Windows" },
    },
  ],
  "smart-home": [
    {
      id: "smart-1",
      name: "Smart Switch & Voice Automation Setup",
      slug: "smart-switch-voice-automation",
      shortDescription: "Convert existing switchboards to Alexa/Google Home smart app control.",
      basePrice: 899,
      discountedPrice: 599,
      duration: 60,
      rating: 4.9,
      reviewCount: 510,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80",
      category: { slug: "smart-home", name: "Smart Home" },
    },
  ],
  "pest-control": [
    {
      id: "pest-1",
      name: "Herbal Cockroach & Ant Control",
      slug: "herbal-cockroach-ant-control",
      shortDescription: "Odorless gel baiting & eco spray treatment with 90-day protection guarantee.",
      basePrice: 899,
      discountedPrice: 699,
      duration: 60,
      rating: 4.8,
      reviewCount: 1120,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      category: { slug: "pest-control", name: "Pest Control" },
    },
  ],
  appliance: [
    {
      id: "app-1",
      name: "Washing Machine Repair & Servicing",
      slug: "washing-machine-repair",
      shortDescription: "Fix spin noise, drum vibration, PCB board, motor, and water inlet valve.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 1350,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80",
      category: { slug: "appliance", name: "Appliance Repair" },
    },
  ],
  marble: [
    {
      id: "marb-1",
      name: "Diamond Italian Marble Polishing",
      slug: "diamond-italian-marble-polishing",
      shortDescription: "Multi-stage diamond pad floor grinding, mirror shine crystallization, and sealant.",
      basePrice: 1499,
      discountedPrice: 999,
      duration: 240,
      rating: 4.9,
      reviewCount: 390,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=600&q=80",
      category: { slug: "marble", name: "Marble Polishing" },
    },
  ],
  "interior-repair": [
    {
      id: "int-1",
      name: "Modular Kitchen Cabinet & Drawer Repair",
      slug: "modular-kitchen-cabinet-repair",
      shortDescription: "Hydraulic hinge replacement, soft-close channel alignment, and drawer repair.",
      basePrice: 499,
      discountedPrice: 349,
      duration: 45,
      rating: 4.8,
      reviewCount: 580,
      isPopular: true,
      thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
      category: { slug: "interior-repair", name: "Interior Repair" },
    },
  ],
};

/* ─── Category Technicians Map ─── */

export const CATEGORY_TECHNICIANS_MAP: Record<string, any[]> = {
  electrical: [
    {
      id: "tech-1",
      displayName: "Suresh Reddy",
      avatar: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&q=80",
      status: "available",
      experience: 7,
      rating: 4.9,
      reviewCount: 340,
      completedJobs: 620,
      serviceRadius: 8,
      specializations: ["Switchboards", "MCB Wiring", "Inverter Setup"],
      verificationStatus: "verified",
    },
    {
      id: "tech-2",
      displayName: "Ramesh Babu",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
      status: "busy",
      experience: 5,
      rating: 4.8,
      reviewCount: 180,
      completedJobs: 390,
      serviceRadius: 12,
      specializations: ["Ceiling Fans", "Chandelier Wiring"],
      verificationStatus: "verified",
    },
  ],
  plumbing: [
    {
      id: "tech-3",
      displayName: "Mahesh Kumar",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
      status: "available",
      experience: 8,
      rating: 4.9,
      reviewCount: 410,
      completedJobs: 850,
      serviceRadius: 6,
      specializations: ["Pipe Leakages", "Bathroom Fittings", "Drain Unclogging"],
      verificationStatus: "verified",
    },
  ],
  ac: [
    {
      id: "tech-4",
      displayName: "Rajesh Varma",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&q=80",
      status: "available",
      experience: 9,
      rating: 4.9,
      reviewCount: 530,
      completedJobs: 1100,
      serviceRadius: 10,
      specializations: ["Foam Jet Washing", "R32 Gas Charging", "Inverter AC"],
      verificationStatus: "verified",
    },
  ],
};

/* ─── Category FAQs Map ─── */

export const CATEGORY_FAQS_MAP: Record<string, any[]> = {
  electrical: [
    {
      question: "Do I need to supply electrical wires or switches?",
      answer: "No, our technician carries high-grade certified wiring, copper switches, and spares. If you already have your own fixtures, we will charge only for installation.",
    },
    {
      question: "Are your electrical repairs covered by a warranty?",
      answer: "Yes! All electrical installations and wiring repairs come with our 30-Day Home-e-Fix Re-work Warranty.",
    },
  ],
  plumbing: [
    {
      question: "What if the leakage starts again after the plumber leaves?",
      answer: "Every plumbing repair is covered by a 30-day leakage warranty. If a leak persists, request a free re-visit via the app, and our senior plumber will fix it.",
    },
  ],
  ac: [
    {
      question: "What is included in Split AC Foam Jet Deep Servicing?",
      answer: "It includes high-pressure foam jet washing of indoor cooling coils, blower wheel, drain tray, air filters, and high-pressure water spray on the outdoor condenser unit.",
    },
    {
      question: "How do I know if my AC requires a gas refill?",
      answer: "Common signs include reduced cooling, ice formation on the indoor unit's copper pipes, or a continuous ticking sound from the compressor.",
    },
  ],
};

/* ─── App Config ─── */

export const APP_CONFIG = {
  name: "Home-e-Fix",
  tagline: "Fixing Homes. Earning Trust.",
  description:
    "Home-e-Fix is your trusted Urban Company–style marketplace for all home services. Book verified professionals for electrical, plumbing, AC, cleaning, painting, and 10+ categories.",
  supportEmail: "support@homeefix.com",
  supportPhone: "+91 1800 123 4567",
  socialLinks: {
    facebook: "https://facebook.com/homeefix",
    instagram: "https://instagram.com/homeefix",
    twitter: "https://twitter.com/homeefix",
    linkedin: "https://linkedin.com/company/homeefix",
    youtube: "https://youtube.com/@homeefix",
  },
  playStoreLink: "#",
  appStoreLink: "#",
} as const;

export const POPULAR_SERVICES = [
  {
    id: "pop-ac-clean",
    name: "Split AC Foam Jet Deep Servicing",
    slug: "split-ac-foam-servicing",
    shortDescription: "Complete indoor & outdoor unit foam cleaning with high-pressure jet spray.",
    basePrice: 699,
    discountedPrice: 499,
    duration: 45,
    rating: 4.8,
    reviewCount: 1420,
    isPopular: true,
    pricingModel: "FIXED" as const,
    pricingLabel: "Fixed Price",
    pricingDetails: "Complete service labor included • No hidden fee",
    warranty: "90-Day Compressor & Cooling Warranty",
    category: { slug: "ac", name: "AC Services" },
    thumbnail: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80",
  },
  {
    id: "pop-plumb-leak",
    name: "Bathroom Leakage & Tap Fitting",
    slug: "bathroom-leakage-tap-repair",
    shortDescription: "Fix leaking taps, flush valves, diverters, and pipe joints with rework guarantee.",
    basePrice: 349,
    discountedPrice: 199,
    duration: 30,
    rating: 4.9,
    reviewCount: 980,
    isPopular: true,
    pricingModel: "STARTING_FROM" as const,
    pricingLabel: "Starting from ₹199",
    pricingDetails: "Standard repair labour charge • Spares extra at MRP",
    warranty: "30-Day Leakage Rework Warranty",
    category: { slug: "plumbing", name: "Plumbing" },
    thumbnail: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
  },
  {
    id: "pop-elec-mcb",
    name: "Switch & Socket Installation / Repair",
    slug: "switch-socket-installation",
    shortDescription: "Replacement of burnt switches, modular sockets, and MCB trip troubleshooting.",
    basePrice: 249,
    discountedPrice: 149,
    duration: 30,
    rating: 4.7,
    reviewCount: 760,
    isPopular: true,
    pricingModel: "PER_UNIT" as const,
    pricingLabel: "₹149 per point",
    pricingDetails: "Installation labour charge • Modular boxes extra if needed",
    warranty: "30-Day Electrical Wiring Warranty",
    category: { slug: "electrical", name: "Electrical" },
    thumbnail: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
  },
  {
    id: "pop-sofa-clean",
    name: "3-Seater Fabric Sofa Shampooing",
    slug: "sofa-shampoo-cleaning",
    shortDescription: "Deep wet-extraction shampooing to remove stubborn stains, allergens & odors.",
    basePrice: 1199,
    discountedPrice: 899,
    duration: 90,
    rating: 4.8,
    reviewCount: 650,
    isPopular: true,
    pricingModel: "FIXED" as const,
    pricingLabel: "Fixed ₹899",
    pricingDetails: "Eco-friendly shampoo & mechanized suction included",
    warranty: "Satisfaction Re-cleaning Cover (24h)",
    category: { slug: "cleaning", name: "Cleaning" },
    thumbnail: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80",
  },
  {
    id: "pop-fan-install",
    name: "Ceiling Fan Assembly & Installation",
    slug: "ceiling-fan-installation",
    shortDescription: "Precision hook mounting, heavy motor balancing, wiring, and speed regulator test.",
    basePrice: 349,
    discountedPrice: 249,
    duration: 45,
    rating: 4.9,
    reviewCount: 820,
    isPopular: false,
    pricingModel: "FIXED" as const,
    pricingLabel: "Fixed ₹249",
    pricingDetails: "Complete mounting labour • Anchor fasteners included",
    warranty: "30-Day Vibration & Noise Guarantee",
    category: { slug: "electrical", name: "Electrical" },
    thumbnail: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&q=80",
  },
  {
    id: "pop-pest-control",
    name: "Herbal Cockroach & Ant Control",
    slug: "herbal-cockroach-ant-control",
    shortDescription: "Odorless herbal gel baiting & crack-and-crevice spray treatment.",
    basePrice: 899,
    discountedPrice: 699,
    duration: 60,
    rating: 4.8,
    reviewCount: 1120,
    isPopular: true,
    pricingModel: "FIXED" as const,
    pricingLabel: "Fixed ₹699",
    pricingDetails: "Odorless, pet-safe herbal gel throughout kitchen & rooms",
    warranty: "90-Day Free Re-treatment Warranty",
    category: { slug: "pest-control", name: "Pest Control" },
    thumbnail: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
  },
];

export const EMERGENCY_SERVICES = [
  {
    id: "emg-burst",
    title: "Major Pipe Burst & Flooding",
    icon: "🚰",
    category: "Plumbing",
    baseInspectionFee: 499,
    description: "Urgent main line shutoff, pressure leakage clamping, and drainage control.",
  },
  {
    id: "emg-power",
    title: "Total Power Blackout / MCB Burnout",
    icon: "⚡",
    category: "Electrical",
    baseInspectionFee: 499,
    description: "Phase short-circuit repair, main breaker trip fix, and emergency wiring.",
  },
  {
    id: "emg-lockout",
    title: "Door Lock Jam / Lockout",
    icon: "🔑",
    category: "Carpentry",
    baseInspectionFee: 499,
    description: "Non-destructive lock opening, mortise cylinder release, and urgent latch repair.",
  },
];

export const WHY_HOMEEFIX = [
  {
    id: "verified-pros",
    icon: "🛡️",
    title: "Verified Professionals",
    description: "Every professional undergoes multi-tier identity verification, police record checks, and practical trade skill assessments.",
    highlight: "100% Background Checked",
  },
  {
    id: "transparent-pricing",
    icon: "💳",
    title: "Transparent Pricing",
    description: "Upfront standard rate cards before service begins. No arbitrary bargaining, hidden transit charges, or surprise extras.",
    highlight: "Standard Rate Cards",
  },
  {
    id: "genuine-materials",
    icon: "⚙️",
    title: "Genuine Materials",
    description: "All replacement parts and spare hardware sourced with manufacturer authenticity, itemized transparently in your digital bill.",
    highlight: "Original Spares",
  },
  {
    id: "service-warranty",
    icon: "✨",
    title: "Service Warranty",
    description: "Every job is backed by a dependable re-work guarantee. If the issue recurs within the warranty window, we fix it free of charge.",
    highlight: "30 to 90 Days Cover",
  },
];

export const OPERATIONAL_PILLARS = [
  {
    id: "digital-invoice",
    title: "Digital Invoice",
    description: "Automated GST-compliant invoices generated directly to your account upon job completion.",
  },
  {
    id: "live-updates",
    title: "Live Booking Updates",
    description: "Real-time dispatch alerts, ETA calculations, and step-by-step service progress notifications.",
  },
  {
    id: "customer-support",
    title: "Customer Support",
    description: "Dedicated support team ready to assist via direct phone hotline and responsive in-app chat.",
  },
  {
    id: "cashless-payment",
    title: "Cashless Payment",
    description: "Pay securely after work inspection via UPI, Debit/Credit Card, Netbanking, or Wallet.",
  },
];

export const HOMEEFIX_GUARANTEE_PILLARS = [
  {
    title: "Verified Professional",
    description: "Assigned technician is background verified with proven trade experience.",
    icon: "🛡️",
  },
  {
    title: "Transparent Pricing",
    description: "Standard upfront rates with itemized labour and spare parts billing.",
    icon: "📋",
  },
  {
    title: "Service Warranty",
    description: "Free re-visit and re-work guarantee across all eligible maintenance jobs.",
    icon: "✨",
  },
  {
    title: "Digital Invoice",
    description: "Instantly accessible GST tax invoices stored safely in your customer dashboard.",
    icon: "🧾",
  },
  {
    title: "Dedicated Support",
    description: "Direct assistance through our helpline and resolution support team.",
    icon: "🎧",
  },
];

export const TESTIMONIALS = [
  {
    userName: "Siddhartha Roy",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80",
    rating: 5,
    date: "August 2026",
    comment: "The AC foam deep cleaning was extremely thorough. The technician showed up on time, cleaned the indoor and outdoor units, and the airflow restored immediately. Clear digital invoice sent right after payment.",
    serviceName: "Split AC Foam Jet Servicing",
    isVerified: true,
    helpfulCount: 34,
  },
  {
    userName: "Ananya Banerjee",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    rating: 5,
    date: "August 2026",
    comment: "Had an urgent bathroom pipe leak in Salt Lake. The plumber arrived with all the necessary copper fittings, replaced the cracked joint, and tested pressure thoroughly. Very professional experience.",
    serviceName: "Bathroom Leakage Repair",
    isVerified: true,
    helpfulCount: 29,
  },
  {
    userName: "Vikram Sen",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    rating: 5,
    date: "July 2026",
    comment: "Booked switchboard replacement and MCB diagnosis. Transparent rate card, no bargaining, and payment via UPI only after checking all light points. Will book again.",
    serviceName: "Switch & Socket Installation",
    isVerified: true,
    helpfulCount: 18,
  },
];

export const BLOG_ARTICLES = [
  {
    id: "blog-ac-maintenance",
    title: "5 Essential Signs Your AC Requires Foam Deep Jet Cleaning",
    category: "AC Care",
    date: "August 2026",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80",
    snippet: "Is your cooling reduced or is moisture dripping from the vents? Learn how regular deep servicing improves air quality and compressor life.",
  },
  {
    id: "blog-monsoon-plumbing",
    title: "Monsoon Home Checklist: Preventing Pipe Clogs & Wall Dampness",
    category: "Plumbing & Civil",
    date: "July 2026",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80",
    snippet: "High humidity and heavy rains can cause drain backups and wall seepage. Here are 4 key preventative checks every homeowner should perform.",
  },
  {
    id: "blog-electrical-safety",
    title: "Understanding MCB Trips & Surge Protection for Modern Homes",
    category: "Electrical Safety",
    date: "June 2026",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=80",
    snippet: "Frequent breaker trips indicate overloaded phases or neutral faults. Discover how timely circuit repair protects expensive electronic appliances.",
  },
];

export const HOMEPAGE_FAQS = [
  {
    question: "How does Home-e-Fix work?",
    answer: "Select your desired home service, pick your preferred date and time slot, and confirm your address. A verified professional is assigned to your booking, arrives with tools and materials, completes the work to high standards, and you pay securely after inspecting the job.",
  },
  {
    question: "Are professionals background verified?",
    answer: "Yes. Every professional on Home-e-Fix undergoes a rigorous onboarding workflow including government ID verification (Aadhaar & PAN), police verification checks, and practical trade skill assessments.",
  },
  {
    question: "What does the service price include?",
    answer: "Our standard prices cover professional labour charges and standard diagnostic assessment. If replacement spare parts or raw materials are required, the technician provides upfront cost estimates based on our standard transparent rate card before installing.",
  },
  {
    question: "Can I reschedule my booking?",
    answer: "Yes, you can easily reschedule your booking directly from your customer dashboard or by contacting support before the technician is dispatched, free of charge.",
  },
  {
    question: "How does cancellation work?",
    answer: "Bookings can be cancelled free of charge prior to technician dispatch. If a cancellation is requested after a technician has arrived on-site, a standard minimum inspection fee applies to compensate the professional for travel and time.",
  },
  {
    question: "What happens if additional materials are required?",
    answer: "Our technician will inspect the requirements on-site and inform you of the necessary parts and prices beforehand. You can either provide the materials yourself or authorize the technician to procure genuine OEM parts with invoice proof.",
  },
  {
    question: "Is there a service warranty?",
    answer: "Yes, most repair and servicing categories include our 30-Day to 90-Day Home-e-Fix Re-work Warranty. If the same issue recurs within the warranty period, we send a technician for a complimentary rework inspection.",
  },
  {
    question: "How do I contact customer support?",
    answer: "Our dedicated support team is available via our toll-free helpline +91 1800 123 4567, email at support@homeefix.com, or through the Help Center in your customer account.",
  },
];

export const BOOKING_STATUSES = {
  pending: { label: "Pending", color: "warning" },
  confirmed: { label: "Confirmed", color: "info" },
  assigned: { label: "Assigned", color: "info" },
  in_progress: { label: "In Progress", color: "accent" },
  completed: { label: "Completed", color: "success" },
  cancelled: { label: "Cancelled", color: "error" },
  refunded: { label: "Refunded", color: "muted" },
} as const;

export const OPERATIONAL_CITIES = {
  activeCity: "Kolkata",
  activeHubs: [
    { id: "kolkata-saltlake", name: "Salt Lake & Sector V", pincode: "700091", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-newtown", name: "New Town & Rajarhat", pincode: "700156", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-parkstreet", name: "Park Street & Camac St", pincode: "700016", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-ballygunge", name: "Ballygunge & Gariahat", pincode: "700019", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-alipore", name: "Alipore & New Alipore", pincode: "700027", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-behala", name: "Behala & Thakurpukur", pincode: "700034", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-dumdum", name: "Dum Dum & Lake Town", pincode: "700028", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-tollygunge", name: "Tollygunge & Jadavpur", pincode: "700033", status: "Active (30-Min Dispatch)" },
    { id: "kolkata-howrah", name: "Howrah & Sibpur", pincode: "711101", status: "Active (30-Min Dispatch)" },
  ],
  upcomingCities: [
    { id: "bengaluru", name: "Bengaluru", status: "Launching Q3 2026" },
    { id: "mumbai", name: "Mumbai", status: "Launching Q3 2026" },
    { id: "delhi", name: "Delhi - NCR", status: "Launching Q4 2026" },
    { id: "hyderabad", name: "Hyderabad", status: "Launching Q4 2026" },
    { id: "pune", name: "Pune", status: "Launching Q4 2026" },
  ],
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 12,
  PAGE_SIZE_OPTIONS: [12, 24, 48, 96],
} as const;
